<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateProfilesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::dropIfExists('profiles');

        Schema::create('profiles', function (Blueprint $table) {
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->integer('country_id');
            $table->integer('locale_id');
            $table->string('name', 150);
            $table->string('implementation_date', 30)->nullable();
            $table->string('applicability', 60)->nullable();
            $table->string('selected_grade', 60)->nullable();
            $table->string('benzene_content', 60)->nullable();
            $table->string('aromatics', 60)->nullable();
            $table->string('olefins', 60)->nullable();
            $table->string('lead_content', 60)->nullable();
            $table->string('magnanese', 60)->nullable();
            $table->string('ron', 60)->nullable();
            $table->string('mon', 60)->nullable();
            $table->string('aki', 60)->nullable();
            $table->string('sulfur_content', 60)->nullable();
            $table->string('oxygen_content', 60)->nullable();
            $table->string('ethanol', 60)->nullable();
            $table->string('rvp_summer', 180)->nullable();
            $table->string('rvp_winter', 180)->nullable();
            $table->string('rvp_transition', 180)->nullable();
            $table->string('mtbe', 180)->nullable();
            $table->string('ethers', 180)->nullable();
            $table->integer('order')->nullable();
            $table->longText('content')->nullable();
            $table->timestamps();
        });

        DB::table('profiles')->insert([
            ['locale_id' => '2', 'order' => '1', 'country_id' => '1', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'North Zone', 'selected_grade' => 'Gasoline Grade 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '1', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'North Zone', 'selected_grade' => 'Gasoline Grade 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '2', 'order' => '3', 'country_id' => '1', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'Central Zone', 'selected_grade' => 'Gasoline Grade 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '<> 45 - 80 kPa', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '2', 'order' => '4', 'country_id' => '1', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'Central Zone', 'selected_grade' => 'Gasoline Grade 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '<> 45 - 80 kPa', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '2', 'order' => '5', 'country_id' => '1', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'South Zone', 'selected_grade' => 'Gasoline Grade 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 45 - 80 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '2', 'order' => '6', 'country_id' => '1', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'South Zone', 'selected_grade' => 'Gasoline Grade 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 45 - 80 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '2', 'name' => 'Supreme Decree 2741', 'implementation_date' => '2016', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 3%v/v (2,7%v/v for E12 in summer)', 'aromatics' => '< 42 % v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 85', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '-', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '2', 'name' => 'Supreme Decree 2741', 'implementation_date' => '2016', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '< 3%v/v (2,7%v/v for E12 in summer)', 'aromatics' => '< 48 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '-', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '3', 'country_id' => '2', 'name' => 'Resolution 121-18', 'implementation_date' => '2018', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline for E8', 'benzene_content' => '< 3%v/v (2,7%v/v for E12 in summer)', 'aromatics' => '< 42 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 85', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< 8 %v/v', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '4', 'country_id' => '2', 'name' => 'Resolution 042-19', 'implementation_date' => '2019', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline for E12', 'benzene_content' => '< 3%v/v (2,7%v/v for E12 in summer)', 'aromatics' => '< 42 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 92', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< 12 %v/v', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '3', 'name' => 'PPDA DS31', 'implementation_date' => '2017', 'applicability' => 'Metropolitan Region', 'selected_grade' => 'G93', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '12 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '93', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'aki' => '', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 55 kPa', 'rvp_winter' => '<> 69 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '3', 'name' => 'PPDA DS31', 'implementation_date' => '2017', 'applicability' => 'Metropolitan Region', 'selected_grade' => 'G97', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '12 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '97', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'aki' => '', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 55 kPa', 'rvp_winter' => '<> 69 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '3', 'country_id' => '3', 'name' => ' DS 60', 'implementation_date' => '2012', 'applicability' => 'Rest of the country', 'selected_grade' => 'G93', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '20 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '93', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'aki' => '', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 69 kPa, <> 83 kPa (Magallanes y región Antártica)', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '4', 'country_id' => '3', 'name' => ' DS 60', 'implementation_date' => '2012', 'applicability' => 'Rest of the country', 'selected_grade' => 'G97', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '20 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '97', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'aki' => '', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 69 kPa, <> 83 kPa (Magallanes y región Antártica)', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '4', 'name' => 'Resolution 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 1,0 %v/v', 'aromatics' => '< 28 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 84', 'mon' => '-', 'aki' => '> 81', 'sulfur_content' => '< 50 mg/kg', 'aki' => '> 81', 'oxygen_content' => '', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '4', 'name' => 'Resolution 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Extra', 'benzene_content' => '< 2,0 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 93', 'mon' => '-', 'aki' => '> 91', 'sulfur_content' => '< 50 mg/kg', 'aki' => '> 91', 'oxygen_content' => '', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '3', 'country_id' => '4', 'name' => 'Resolution 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Regular E10', 'benzene_content' => '< 0,9 %v/v', 'aromatics' => '< 25 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 89', 'mon' => '-', 'aki' => '> 84', 'sulfur_content' => '< 50 mg/kg', 'aki' => '> 84', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '4', 'country_id' => '4', 'name' => 'Resolution 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Extra E10', 'benzene_content' => '< 1,8 %v/v', 'aromatics' => '< 31,5 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 97', 'mon' => '-', 'aki' => '> 94', 'sulfur_content' => '< 50 mg/kg', 'aki' => '> 94', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '5', 'name' => 'INTE E1:2019', 'implementation_date' => '2019', 'applicability' => 'Whole country', 'selected_grade' => 'RON 91', 'benzene_content' => '< 1,5% v/v', 'aromatics' => '< 35% v/v', 'olefins' => '< 18% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 91', 'mon' => '> 79', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% m/m (3,7% m/m if ethanol is added)', 'ethanol' => '< 10% v/v', 'rvp_summer' => '< 69 kPa (< 76 kPa if ethanol is added)', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '5', 'name' => 'INTE E1:2019', 'implementation_date' => '2019', 'applicability' => 'Whole country', 'selected_grade' => 'RON 95', 'benzene_content' => '< 1,5% v/v', 'aromatics' => '< 35% v/v', 'olefins' => '< 18% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 95', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% m/m (3,7% m/m if ethanol is added)', 'ethanol' => '< 10% v/v', 'rvp_summer' => '< 69 kPa (< 76 kPa if ethanol is added)', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => ''],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '15', 'name' => 'NORDOM 476 3rd Revision', 'implementation_date' => '2015', 'applicability' => 'Whole country', 'selected_grade' => 'Regular Gasoline', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 89', 'mon' => '> 76', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '', 'oxygen_content' => '', 'ethanol' => '', 'rvp_summer' => '< 61 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '15', 'name' => 'NORDOM 476 3rd Revision', 'implementation_date' => '2015', 'applicability' => 'Whole country', 'selected_grade' => 'Premium Gasoline', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 95', 'mon' => '> 82', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '', 'oxygen_content' => '', 'ethanol' => '', 'rvp_summer' => '< 61 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '3', 'country_id' => '15', 'name' => 'NORDOM 476 3rd Revision', 'implementation_date' => '2015', 'applicability' => 'Whole country', 'selected_grade' => 'Oxigenated Regular Gasoline', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 90', 'mon' => '> 77', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '', 'oxygen_content' => '< 3.5 %m/m', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '4', 'country_id' => '15', 'name' => 'NORDOM 476 3rd Revision', 'implementation_date' => '2015', 'applicability' => 'Whole country', 'selected_grade' => 'Oxigenated Premium Gasoline', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 96', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '', 'oxygen_content' => '< 3.5 %m/m', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '6', 'name' => 'NTE INEN 935:2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'RON 85', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 30 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0 mg/l', 'magnanese' => '0 mg/l', 'ron' => '85', 'mon' => '', 'aki' => '', 'sulfur_content' => '650 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '', 'rvp_summer' => '<60 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '6', 'name' => 'NTE INEN 935:2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'RON 89', 'benzene_content' => '< 2 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 25 %v/v', 'lead_content' => '< 0 mg/l', 'magnanese' => '0 mg/l', 'ron' => '89', 'mon' => '', 'aki' => '', 'sulfur_content' => '650 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '', 'rvp_summer' => '<60 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '3', 'country_id' => '6', 'name' => 'NTE INEN 935:2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'RON 92', 'benzene_content' => '<2 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 25 %v/v', 'lead_content' => '< 0 mg/l', 'magnanese' => '0 mg/l', 'ron' => '92', 'mon' => '', 'aki' => '', 'sulfur_content' => '450 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '', 'rvp_summer' => '<60 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '4', 'country_id' => '6', 'name' => 'NTE INEN 935:2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'RON 93', 'benzene_content' => '<1,3 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 25 %v/v', 'lead_content' => '< 0 mg/l', 'magnanese' => '0 mg/l', 'ron' => '95', 'mon' => '', 'aki' => '', 'sulfur_content' => '<300 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '', 'rvp_summer' => '<62 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '7', 'name' => 'RTCA 75.01.19:19', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '2,0% v/v', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '0,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '7', 'name' => 'RTCA 75.01.20:19', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '2,0% v/v', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '0,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '23', 'name' => 'EN 228:2012 + A1:2017 (Euro 6 enabling)', 'implementation_date' => '2017', 'applicability' => 'All countries', 'selected_grade' => 'RON 95 E5', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 95', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '<2,7 % m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 60 - 70 kPa *Depends on the country, RVP is regulated in the EU Fuel Quality Directive', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => 'Based on oxygen content'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '23', 'name' => 'EN 228:2012 + A1:2017 (Euro 6 enabling)', 'implementation_date' => '2017', 'applicability' => 'All countries', 'selected_grade' => 'RON 95 E10', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 95', 'mon' => '> 88', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '<3,7 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '<> 60 - 70 kPa *Depends on the country, RVP is regulated in the EU Fuel Quality Directive', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '<22 %v/v'],
            ['locale_id' => '2', 'order' => '3', 'country_id' => '23', 'name' => 'EN 228:2012 + A1:2017 (Euro 6 enabling)', 'implementation_date' => '2017', 'applicability' => 'All countries', 'selected_grade' => 'RON 98 E5', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 98', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '<2,7 % m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 60 - 70 kPa *Depends on the country, RVP is regulated in the EU Fuel Quality Directive', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => 'Based on oxygen content'],
            ['locale_id' => '2', 'order' => '4', 'country_id' => '23', 'name' => 'EN 228:2012 + A1:2017 (Euro 6 enabling)', 'implementation_date' => '2017', 'applicability' => 'All countries', 'selected_grade' => 'RON 98 E10', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 98', 'mon' => '> 88', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '<3,7 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '<> 60 - 70 kPa *Depends on the country, RVP is regulated in the EU Fuel Quality Directive', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '<22 %v/v'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '8', 'name' => 'Ministerial Accord Number 320-2022', 'implementation_date' => '2022', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 2,5% v/v', 'aromatics' => '- / < 50% v/v', 'olefins' => '- / < 30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '-', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '10% v/v', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '8', 'name' => 'Ministerial Accord Number 320-2022', 'implementation_date' => '2022', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Superior', 'benzene_content' => '< 2,5% v/v', 'aromatics' => '- / < 50% v/v', 'olefins' => '- / < 30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '-', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '10% v/v', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '9', 'name' => 'RTCA 75.01.08:19 p.m.', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '2,5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '0,25% v/v', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '9', 'name' => 'RTCA 75.01.19:19', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '2,5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '0,25% v/v', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '10', 'name' => 'JS 341:2017', 'implementation_date' => '2017', 'applicability' => 'Whole country', 'selected_grade' => 'Unleaded Petrol AKI 87 E10', 'benzene_content' => '< 5 %v/v', 'aromatics' => '< 45 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '', 'mon' => '', 'aki' => '90', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '90', 'oxygen_content' => '< 4 %m/m (Gasoline with no ethanol)', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 61 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '< 15% v/v for Gasoline with no ethanol', 'ethers' => '15% v/v (other oxygenates)'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '10', 'name' => 'JS 341:2017', 'implementation_date' => '2017', 'applicability' => 'Whole country', 'selected_grade' => 'Unleaded Petrol AKI 90 E10', 'benzene_content' => '< 5 %v/v', 'aromatics' => '< 45 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '', 'mon' => '', 'aki' => '87', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '87', 'oxygen_content' => '< 4 %m/m (Gasoline with no ethanol)', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '< 15% v/v for Gasoline with no ethanol', 'ethers' => '15% v/v (other oxygenates)'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Mexico City', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 25 %v/v ', 'olefins' => '< 10 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => 'Not allowed', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa ', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Mexico City', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 25 %v/v ', 'olefins' => '< 10 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => 'Not allowed', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa ', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '3', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Guadalajara and Monterrey', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 32 %v/v', 'olefins' => '< 11,9 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => 'Not allowed', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa  Guadalajara', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '4', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Guadalajara and Monterrey', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '22,6% v/v', 'olefins' => '< 11,9 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => 'Not allowed', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa  Guadalajara', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '5', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Rest of the country', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 2 %v/v ', 'aromatics' => 'Report', 'olefins' => 'Report', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '> 5,8 %v/v', 'rvp_summer' => '< 69 kPa North, < 62 kPa Center, South, Pacific', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '6', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Rest of the country', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '< 2 %v/v ', 'aromatics' => '22,6% v/v', 'olefins' => '< 2,5 mg/l', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '> 5,8 %v/v', 'rvp_summer' => '< 69 kPa North, < 62 kPa Center, South, Pacific', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '12', 'name' => 'RTCA 75.01.20:19', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Report', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '12', 'name' => 'RTCA 75.01.19:19', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Report', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '13', 'name' => 'DGNTI-COPANIT 83-2013/ Resolution 425/2020', 'implementation_date' => '2014/2021', 'applicability' => 'Whole country', 'selected_grade' => 'RON 91', 'benzene_content' => '< 5% v/v / <1,5% v/v', 'aromatics' => '< 50% v/v', 'olefins' => '< 30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg / < 150 mg/kg', 'aki' => '', 'oxygen_content' => '-/ < 0,7% v/v', 'ethanol' => '10% v/v', 'rvp_summer' => '< 69 kPa (< 76 kPa if ethanol is added)', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '0% v/v if ethanol is added', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '13', 'name' => 'DGNTI-COPANIT 83-2013/ Resolution 425/2020', 'implementation_date' => '2014/2021', 'applicability' => 'Whole country', 'selected_grade' => 'RON 95', 'benzene_content' => '< 5% v/v / <1,5% v/v', 'aromatics' => '< 50% v/v', 'olefins' => '< 30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg / < 150 mg/kg', 'aki' => '', 'oxygen_content' => '-/ < 0,7% v/v', 'ethanol' => '10% v/v', 'rvp_summer' => '< 69 kPa (< 76 kPa if ethanol is added)', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '0% v/v if ethanol is added', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '14', 'name' => 'Ministerial Resolution Nº 469-2021-MINEM/DM', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasolina Regular', 'benzene_content' => '< 2% v/v', 'aromatics' => '< 45% v/v', 'olefins' => '< 25% v/v ', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 0,25 mg/l', 'ron' => '> 90', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => 'Reportar', 'ethanol' => '', 'rvp_summer' => '< 76 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '14', 'name' => 'Ministerial Resolution Nº 469-2021-MINEM/DM', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasolina Premium', 'benzene_content' => '< 2% v/v', 'aromatics' => '< 45% v/v', 'olefins' => '< 25% v/v ', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 0,25 mg/l', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => 'Reportar', 'ethanol' => '', 'rvp_summer' => '< 76 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '3', 'country_id' => '14', 'name' => 'Ministerial Resolution Nº 469-2021-MINEM/DM', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasohol Regular', 'benzene_content' => '< 2% v/v', 'aromatics' => '< 45% v/v', 'olefins' => '< 25% v/v ', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 0,25 mg/l', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => '< 3,45 %m/m', 'ethanol' => '< 7,8 %v/v', 'rvp_summer' => '< 76 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '4', 'country_id' => '14', 'name' => 'Ministerial Resolution Nº 469-2021-MINEM/DM', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasohol Premium', 'benzene_content' => '< 2% v/v', 'aromatics' => '< 45% v/v', 'olefins' => '< 25% v/v ', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 0,25 mg/l', 'ron' => '> 96', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => '< 3,45 %m/m', 'ethanol' => '< 7,8 %v/v', 'rvp_summer' => '< 76 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '1', 'country_id' => '16', 'name' => 'Resolution 110/2014', 'implementation_date' => '2019', 'applicability' => 'Whole country', 'selected_grade' => 'Super 95 30-S', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '< 20 %v/v', 'lead_content' => '< 0,005 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 95', 'mon' => '> 82', 'aki' => '', 'sulfur_content' => '< 30 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< > 10 %v/v', 'rvp_summer' => '<> 72 kPa', 'rvp_winter' => '<> 83 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '2', 'country_id' => '16', 'name' => 'Resolution 110/2014', 'implementation_date' => '2019', 'applicability' => 'Whole country', 'selected_grade' => 'Premium 97 30-S', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '< 20 %v/v', 'lead_content' => '< 0,005 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 97', 'mon' => '> 84', 'aki' => '', 'sulfur_content' => '< 30 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< > 10 %v/v', 'rvp_summer' => '<> 72 kPa', 'rvp_winter' => '<> 83 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '3', 'country_id' => '16', 'name' => 'ANCAP', 'implementation_date' => '2020', 'applicability' => 'Whole country', 'selected_grade' => 'Super 95 30-S', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,005 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 95', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '', 'rvp_summer' => '<> 50-80 kPa', 'rvp_winter' => '<> 45-67 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '2', 'order' => '4', 'country_id' => '16', 'name' => 'ANCAP', 'implementation_date' => '2020', 'applicability' => 'Whole country', 'selected_grade' => 'Premium 97 30-S', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,005 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 97', 'mon' => '> 86', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '', 'rvp_summer' => '<> 50-80 kPa', 'rvp_winter' => '<> 45-67 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],

            ['locale_id' => '4', 'order' => '1', 'country_id' => '1', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Norte', 'selected_grade' => 'Gasolina Grado 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '1', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Norte', 'selected_grade' => 'Gasolina Grado 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '4', 'order' => '3', 'country_id' => '1', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Central', 'selected_grade' => 'Gasolina Grado 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '<> 45 - 80 kPa', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '4', 'order' => '4', 'country_id' => '1', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Central', 'selected_grade' => 'Gasolina Grado 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '<> 45 - 80 kPa', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '4', 'order' => '5', 'country_id' => '1', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Sur', 'selected_grade' => 'Gasolina Grado 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 45 - 80 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '4', 'order' => '6', 'country_id' => '1', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Sur', 'selected_grade' => 'Gasolina Grado 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 45 - 80 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '2', 'name' => 'Decreto supremo 2741', 'implementation_date' => '2016', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '< 3%v/v (2,7%v/v para E12 en verano)', 'aromatics' => '< 42 % v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 85', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '-', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '2', 'name' => 'Decreto supremo 2741', 'implementation_date' => '2016', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '< 3%v/v (2,7%v/v para E12 en verano)', 'aromatics' => '< 48 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '-', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '3', 'country_id' => '2', 'name' => 'Resolución 121-18', 'implementation_date' => '2018', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina para E8', 'benzene_content' => '< 3%v/v (2,7%v/v para E12 en verano)', 'aromatics' => '< 42 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 85', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< 8 %v/v', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '4', 'country_id' => '2', 'name' => 'Resolución 042-19', 'implementation_date' => '2019', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina para E12', 'benzene_content' => '< 3%v/v (2,7%v/v para E12 en verano)', 'aromatics' => '< 42 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 92', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< 12 %v/v', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '15', 'name' => 'NORDOM 476 3era Revision', 'implementation_date' => '2015', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Regular', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 89', 'mon' => '> 76', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '', 'oxygen_content' => '', 'ethanol' => '', 'rvp_summer' => '< 61 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '15', 'name' => 'NORDOM 476 3era Revision', 'implementation_date' => '2015', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Premium', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 95', 'mon' => '> 82', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '', 'oxygen_content' => '', 'ethanol' => '', 'rvp_summer' => '< 61 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '3', 'country_id' => '15', 'name' => 'NORDOM 476 3era Revision', 'implementation_date' => '2015', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina regular oxigenada', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 90', 'mon' => '> 77', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '', 'oxygen_content' => '< 3.5 %m/m', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '4', 'country_id' => '15', 'name' => 'NORDOM 476 3era Revision', 'implementation_date' => '2015', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina premium oxigenada', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 96', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '', 'oxygen_content' => '< 3.5 %m/m', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '10', 'name' => 'JS 341:2017', 'implementation_date' => '2017', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina sin plomo AKI 87 E10', 'benzene_content' => '< 5 %v/v', 'aromatics' => '< 45 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '', 'mon' => '', 'aki' => '90', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '90', 'oxygen_content' => '< 4 %m/m (gasolina con etanol)', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 61 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '< 15% v/v para gasolina sin etanol', 'ethers' => '15% v/v (otros oxigenantes)'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '10', 'name' => 'JS 341:2017', 'implementation_date' => '2017', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina sin plomo AKI 90 E10', 'benzene_content' => '< 5 %v/v', 'aromatics' => '< 45 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '', 'mon' => '', 'aki' => '87', 'sulfur_content' => '< 1.500 mg/kg', 'aki' => '87', 'oxygen_content' => '< 4 %m/m (gasolina con etanol)', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '< 15% v/v para gasolina sin etanol', 'ethers' => '15% v/v (otros oxigenantes)'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '5', 'name' => 'INTE E1:2019', 'implementation_date' => '2019', 'applicability' => 'Todo el país', 'selected_grade' => 'RON 91', 'benzene_content' => '< 1,5% v/v', 'aromatics' => '< 35% v/v', 'olefins' => '< 18% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 91', 'mon' => '> 79', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% m/m (3,7% m/m si se añade etanol)', 'ethanol' => '< 10% v/v', 'rvp_summer' => '< 69 kPa (< 76 kPa si se añade etanol)', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '5', 'name' => 'INTE E1:2019', 'implementation_date' => '2019', 'applicability' => 'Todo el país', 'selected_grade' => 'RON 95', 'benzene_content' => '< 1,5% v/v', 'aromatics' => '< 35% v/v', 'olefins' => '< 18% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 95', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% m/m (3,7% m/m si se añade etanol)', 'ethanol' => '< 10% v/v', 'rvp_summer' => '< 69 kPa (< 76 kPa si se añade etanol)', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => ''],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '8', 'name' => 'Acuerdo Ministerial Número 320-2022', 'implementation_date' => '2022', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '< 2,5% v/v', 'aromatics' => '- / < 50% v/v', 'olefins' => '- / < 30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => ' > 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '-', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '10% v/v', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '8', 'name' => 'Acuerdo Ministerial Número 320-2022', 'implementation_date' => '2022', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina superior', 'benzene_content' => '< 2,5% v/v', 'aromatics' => '- / < 50% v/v', 'olefins' => '- / < 30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '-', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '10% v/v', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '7', 'name' => 'RTCA 75.01.19:19', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '2,0% v/v', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '0,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '7', 'name' => 'RTCA 75.01.20:19', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '2,0% v/v', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '0,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '9', 'name' => 'RTCA 75.01.08:19 p.m.', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '2,5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '0,25% v/v', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '9', 'name' => 'RTCA 75.01.19:19', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '2,5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '0,25% v/v', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '12', 'name' => 'RTCA 75.01.20:19', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reporte', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '12', 'name' => 'RTCA 75.01.19:19', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '5% v/v', 'aromatics' => '50% v/v', 'olefins' => '30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reporte', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'aki' => '', 'oxygen_content' => '2,7% v/v', 'ethanol' => '-', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '13', 'name' => 'DGNTI-COPANIT 83-2013/ Resolución 425/2020', 'implementation_date' => '2014/2021', 'applicability' => 'Todo el país', 'selected_grade' => 'RON 91', 'benzene_content' => '< 5% v/v / <1,5% v/v', 'aromatics' => '< 50% v/v', 'olefins' => '< 30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg / < 150 mg/kg', 'aki' => '', 'oxygen_content' => '-/ < 0,7% v/v', 'ethanol' => '10% v/v', 'rvp_summer' => '< 69 kPa (< 76 kPa si se añade etanol)', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '0% v/v si se añade etanol', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '13', 'name' => 'DGNTI-COPANIT 83-2013/ Resolución 425/2020', 'implementation_date' => '2014/2021', 'applicability' => 'Todo el país', 'selected_grade' => 'RON 95', 'benzene_content' => '< 5% v/v / <1,5% v/v', 'aromatics' => '< 50% v/v', 'olefins' => '< 30% v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg / < 150 mg/kg', 'aki' => '', 'oxygen_content' => '-/ < 0,7% v/v', 'ethanol' => '10% v/v', 'rvp_summer' => '< 69 kPa (< 76 kPa si se añade etanol)', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '0% v/v si se añade etanol', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '3', 'name' => 'PPDA DS31', 'implementation_date' => '2017', 'applicability' => 'Region Metropolitana', 'selected_grade' => 'G93', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '12 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '93', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'aki' => '', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 55 kPa', 'rvp_winter' => '<> 69 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '3', 'name' => 'PPDA DS31', 'implementation_date' => '2017', 'applicability' => 'Region Metropolitana', 'selected_grade' => 'G97', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '12 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '97', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'aki' => '', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 55 kPa', 'rvp_winter' => '<> 69 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '3', 'country_id' => '3', 'name' => ' DS 60', 'implementation_date' => '2012', 'applicability' => 'Resto del país', 'selected_grade' => 'G93', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '20 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '93', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'aki' => '', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 69 kPa, <> 83 kPa (Magallanes y región Antártica)', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => ''],
            ['locale_id' => '4', 'order' => '4', 'country_id' => '3', 'name' => ' DS 60', 'implementation_date' => '2012', 'applicability' => 'Resto del país', 'selected_grade' => 'G97', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '20 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '97', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'aki' => '', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 69 kPa, <> 83 kPa (Magallanes y región Antártica)', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => ''],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '4', 'name' => 'Resolución 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Corriente', 'benzene_content' => '< 1,0 %v/v', 'aromatics' => '< 28 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 84', 'mon' => '-', 'aki' => '> 81', 'sulfur_content' => '< 50 mg/kg', 'aki' => '> 81', 'oxygen_content' => '', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '4', 'name' => 'Resolución 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Extra', 'benzene_content' => '< 2,0 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 93', 'mon' => '-', 'aki' => '> 91', 'sulfur_content' => '< 50 mg/kg', 'aki' => '> 91', 'oxygen_content' => '', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '3', 'country_id' => '4', 'name' => 'Resolución 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Corriente E10', 'benzene_content' => '< 0,9 %v/v', 'aromatics' => '< 25 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 89', 'mon' => '-', 'aki' => '> 84', 'sulfur_content' => '< 50 mg/kg', 'aki' => '> 84', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '4', 'country_id' => '4', 'name' => 'Resolución 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Extra E10', 'benzene_content' => '< 1,8 %v/v', 'aromatics' => '< 31,5 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 97', 'mon' => '-', 'aki' => '> 94', 'sulfur_content' => '< 50 mg/kg', 'aki' => '> 94', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '6', 'name' => 'NTE INEN 935:2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'RON 85', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 30 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0 mg/l', 'magnanese' => '0 mg/l', 'ron' => '85', 'mon' => '', 'aki' => '', 'sulfur_content' => '650 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m (para gasolina con etanol)', 'ethanol' => '', 'rvp_summer' => '<60 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '6', 'name' => 'NTE INEN 935:2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'RON 89', 'benzene_content' => '< 2 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 25 %v/v', 'lead_content' => '< 0 mg/l', 'magnanese' => '0 mg/l', 'ron' => '89', 'mon' => '', 'aki' => '', 'sulfur_content' => '650 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m (para gasolina con etanol)', 'ethanol' => '', 'rvp_summer' => '<60 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '3', 'country_id' => '6', 'name' => 'NTE INEN 935:2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'RON 92', 'benzene_content' => '<2 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 25 %v/v', 'lead_content' => '< 0 mg/l', 'magnanese' => '0 mg/l', 'ron' => '92', 'mon' => '', 'aki' => '', 'sulfur_content' => '450 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m (para gasolina con etanol)', 'ethanol' => '', 'rvp_summer' => '<60 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '4', 'country_id' => '6', 'name' => 'NTE INEN 935:2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'RON 93', 'benzene_content' => '<1,3 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 25 %v/v', 'lead_content' => '< 0 mg/l', 'magnanese' => '0 mg/l', 'ron' => '95', 'mon' => '', 'aki' => '', 'sulfur_content' => '<300 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m (para gasolina con etanol)', 'ethanol' => '', 'rvp_summer' => '<62 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Ciudad de México', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 25 %v/v ', 'olefins' => '< 10 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => 'No se permite ', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa ', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Ciudad de México', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 25 %v/v ', 'olefins' => '< 10 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => 'No se permite ', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa ', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '3', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Guadalajara y Monterrey', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 32 %v/v', 'olefins' => '< 11,9 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => 'No se permite ', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa  Guadalajara', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '4', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Guadalajara y Monterrey', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '22,6% v/v', 'olefins' => '< 11,9 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => 'No se permite ', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa  Guadalajara', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '5', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Resto del país', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '< 2 %v/v ', 'aromatics' => 'Reporte', 'olefins' => 'Reporte', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '> 5,8 %v/v', 'rvp_summer' => '< 69 kPa Norte, < 62 kPa centro, sur, Pacífico', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '6', 'country_id' => '11', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Resto del país', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '< 2 %v/v ', 'aromatics' => '22,6% v/v', 'olefins' => '< 2,5 mg/l', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '> 5,8 %v/v', 'rvp_summer' => '< 69 kPa Norte, < 62 kPa centro, sur, Pacífico', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '14', 'name' => 'Ministerial Resolution Nº 469-2021-MINEM/DM', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Regular', 'benzene_content' => '< 2% v/v', 'aromatics' => '< 45% v/v', 'olefins' => '< 25% v/v ', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 0,25 mg/l', 'ron' => '> 90', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => 'Reportar', 'ethanol' => '', 'rvp_summer' => '< 76 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '14', 'name' => 'Ministerial Resolution Nº 469-2021-MINEM/DM', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Premium', 'benzene_content' => '< 2% v/v', 'aromatics' => '< 45% v/v', 'olefins' => '< 25% v/v ', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 0,25 mg/l', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => 'Reportar', 'ethanol' => '', 'rvp_summer' => '< 76 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '3', 'country_id' => '14', 'name' => 'Ministerial Resolution Nº 469-2021-MINEM/DM', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasohol Regular', 'benzene_content' => '< 2% v/v', 'aromatics' => '< 45% v/v', 'olefins' => '< 25% v/v ', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 0,25 mg/l', 'ron' => '> 91', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => '< 3,45 %m/m', 'ethanol' => '< 7,8 %v/v', 'rvp_summer' => '< 76 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '4', 'country_id' => '14', 'name' => 'Ministerial Resolution Nº 469-2021-MINEM/DM', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasohol Premium', 'benzene_content' => '< 2% v/v', 'aromatics' => '< 45% v/v', 'olefins' => '< 25% v/v ', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 0,25 mg/l', 'ron' => '> 96', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'aki' => '', 'oxygen_content' => '< 3,45 %m/m', 'ethanol' => '< 7,8 %v/v', 'rvp_summer' => '< 76 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '16', 'name' => 'Resolución 110/2014', 'implementation_date' => '2019', 'applicability' => 'Todo el país', 'selected_grade' => 'Súper 95 30-S', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '< 20 %v/v', 'lead_content' => '< 0,005 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 95', 'mon' => '> 82', 'aki' => '', 'sulfur_content' => '< 30 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< > 10 %v/v', 'rvp_summer' => '<> 72 kPa', 'rvp_winter' => '<> 83 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '16', 'name' => 'Resolución 110/2014', 'implementation_date' => '2019', 'applicability' => 'Todo el país', 'selected_grade' => 'Premium 97 30-S', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '< 20 %v/v', 'lead_content' => '< 0,005 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 97', 'mon' => '> 84', 'aki' => '', 'sulfur_content' => '< 30 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< > 10 %v/v', 'rvp_summer' => '<> 72 kPa', 'rvp_winter' => '<> 83 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '3', 'country_id' => '16', 'name' => 'ANCAP', 'implementation_date' => '2020', 'applicability' => 'Todo el país', 'selected_grade' => 'Súper 95 30-S', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,005 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 95', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '', 'rvp_summer' => '<> 50-80 kPa', 'rvp_winter' => '<> 45-67 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '4', 'country_id' => '16', 'name' => 'ANCAP', 'implementation_date' => '2020', 'applicability' => 'Todo el país', 'selected_grade' => 'Premium 97 30-S', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,005 g/l', 'magnanese' => '< 2,5 mg/l', 'ron' => '> 97', 'mon' => '> 86', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '', 'rvp_summer' => '<> 50-80 kPa', 'rvp_winter' => '<> 45-67 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-'],
            ['locale_id' => '4', 'order' => '1', 'country_id' => '23', 'name' => 'EN 228:2012 + A1:2017 (autorización Euro 6)', 'implementation_date' => '2017', 'applicability' => 'Todos los países', 'selected_grade' => 'RON 95 E5', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 95', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '<2,7 % m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 60 - 70 kPa *Depende del país, la PVR está regulada en la Directiva de la calidad del combustible de la UE', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => 'Con base en contenido de oxígeno'],
            ['locale_id' => '4', 'order' => '2', 'country_id' => '23', 'name' => 'EN 228:2012 + A1:2017 (autorización Euro 6)', 'implementation_date' => '2017', 'applicability' => 'Todos los países', 'selected_grade' => 'RON 95 E10', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 95', 'mon' => '> 88', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '<3,7 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '<> 60 - 70 kPa *Depende del país, la PVR está regulada en la Directiva de la calidad del combustible de la UE', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '<22 %v/v'],
            ['locale_id' => '4', 'order' => '3', 'country_id' => '23', 'name' => 'EN 228:2012 + A1:2017 (autorización Euro 6)', 'implementation_date' => '2017', 'applicability' => 'Todos los países', 'selected_grade' => 'RON 98 E5', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 98', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '<2,7 % m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 60 - 70 kPa *Depende del país, la PVR está regulada en la Directiva de la calidad del combustible de la UE', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => 'Con base en contenido de oxígeno'],
            ['locale_id' => '4', 'order' => '4', 'country_id' => '23', 'name' => 'EN 228:2012 + A1:2017 (autorización Euro 6)', 'implementation_date' => '2017', 'applicability' => 'Todos los países', 'selected_grade' => 'RON 98 E10', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 98', 'mon' => '> 88', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'aki' => '', 'oxygen_content' => '<3,7 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '<> 60 - 70 kPa *Depende del país, la PVR está regulada en la Directiva de la calidad del combustible de la UE', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '-', 'ethers' => '<22 %v/v']

        ]);
    }
}
