<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateDynamicToolsTextsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::dropIfExists('dynamic_tools_texts');

        Schema::create('dynamic_tools_texts', function (Blueprint $table) {
            $table->collation = 'utf8mb4_unicode_ci';
            $table->id();
            $table->integer('locale_id');
            $table->integer('country_id');
            $table->string('key', 150);
            $table->longText('content');
            $table->timestamps();  
        });

        DB::table('dynamic_tools_texts')->insert([
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '1', 'content' => 'La demanda de gasolinas en Argentina fue poco más de 2,500 millones de galones en 2022 (9,000 millones de litros). Se cuenta con la siguiente participación por tipo de gasolina: 75% como Nafta Súper / Grado 2 (RON 93 – AKI 87) y 25% restante como Nafta Ultra / Grado 3 (RON 97 – AKI 92). Argentina produce casi la totalidad de la gasolina, las importaciones son menos de 250 millones de litros por año.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '2', 'content' => 'En 2022, el consumo de gasolina fue de 528 millones de galones (2,000 millones de litros). Se importó el 38.4% de la demanda, principalmente de Brazil, Chile, Estados Unidos y Argentina. La producción se ha mantenido prácticamente constante en los últimos cuatro años. El 96% de la demanda es Gasolina Especial (regular) con un octanaje RON de 85 y el resto es Gasolina Premium con un octanaje RON de 95.  Se espera la oferta de gasolinas con octanaje intermedio en el corto plazo.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '3', 'content' => 'El consumo de gasolinas en Chile ya ha superado los 1,400 millones de galones por año (5,000 millones de litros), repartidos entre los tres grados que se comercializan:  RON 93 (AKI 87), RON 95 (AKI 88) y RON 97 (AKI 92).  El grado RON 93 representa el 28% del mercado de gasolinas. Chile cuenta con una especificación especial para la Región Metropolitana de Santiago que es más estricta que la del resto del país. La empresa del estado, ENAP, produce el 80% del consumo en Chile. En 2022 se redujo la producción por mantenimiento y restricciones ambientales en refinerías. Las importaciones de gasolina y componentes provienen principalmente de Estados Unidos. Aunque en las refinerías sólo producen RON 93 y RON 97, en Estaciones de Servicio mezclan por partes iguales ambas gasolinas para producir RON 95.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '4', 'content' => 'En 2022, la demanda de gasolinas en Colombia fue cercana a 1,800 millones de galones (6,800 millones de litros). Actualmente la gasolina Extra E10 (RON 97 – AKI 94) solo participa un 3%, mientras que el 97% restante domina la gasolina Corriente E10 (RON  89 – AKI 84). Colombia tiene una producción que suministra el 65% del consumo nacional, por lo que se recurre aimportaciones con países extranjeros, entre ellos Estados Unidos.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '5', 'content' => 'Costa Rica cuenta con dos gasolinas RON 95 y RON 91, con una participación de mercado de 51%  RON 91 y 49% RON 95  en 2022. Al no contar con refinación, el mezclado de sus gasolinas se realiza únicamente con importaciones provenientes principalmente de Estados Unidos y en menor grado de Europa.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '6', 'content' => 'El mercado nacional de gasolinas en Ecuador alcanzó los 1,200 millones de galones (4,500 millones de litros) para 2022. Actualmente, se decretó un nuevo plan de implementación de nuevas gasolinas, donde existen oficialmente 4 grados de gasolina en 5 diferentes tipos: Gasolina Extra (RON 85), Gasolina Ecopais E10 (RON 85), Gasolina Ecoplus (RON 89), Gasolina Súper (RON 92), Gasolina Súper Premium (RON 95). La G. Super Premium (RON 95) sustituiría paulatinamente a la G. Súper (RON 92); mientras que se ha lanzado un plan piloto para la nueva gasolina Ecoplus (RON 89). Ecuador cuenta con producción propia e importa naftas (gasolinas no terminadas) para cubrir su demanda interna. '],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '7', 'content' => 'En 2022, la demanda de gasolina fue 315 millones de galones (1,180 millones de litros).  La gasolina regular RON 91 representó el 50.6% del volumen consumido mientras que la gasolina superior RON 95 alcanzó un 49.4%. La gasolina se importa en su totalidad y  se distribuye principalmente por las compañías Chevron, Puma y Uno; teniendo como origen importaciones desde Estados Unidos.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '8', 'content' => 'La demanda de gasolina fue de 670 millones de galones en 2022 (2,550 millones de litros).Se cuentan con dos especificaciones de gasolina: Regular (RON 91 - AKI 85) y Superior (RON 95 - AKI 89). El 60% del consumo es gasolina Regular. Guatemala no cuenta con una producción nacional de gasolinas, por lo que recurre totalmente a importaciones princpalmente desde Estados Unidos.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '9', 'content' => 'En 2022, la demanda de gasolina fue de 314 millones de galones  (1,190 milliones litros). La gasolina Regular RON 91 representó el 44.6% mientras que la gasolina Superior RON 95 el 55.6% del consumo nacional. No cuenta con producción de gasolinas, obteniendo los componentes de mezcla principalmente de importaciones de Estados Unidos.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '10', 'content' => 'En 2022, la participación de la gasolina regular (AKI 87) fue de 36% y de la gasolina premium (AKI 90) de 64%.  La producción de gasolina alcanza 476  millones de litros  e importa 190 millones principalmente de Estados Unidos. Desde 2010 solo se consume gasolina E10. '],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '11', 'content' => 'La demanda de gasolina en México es de 12,500 millones de galones por año (20,000 millones de litros). Actualmente existen dos grados de octanaje: Regular (AKI 87) y Premium (AKI 91). La gasolina regular es la de mayor consumo con una participación del 90%. Adicionalmente existen especificaciones mas estrictas para las Zonas Metropolitanas (Ciudad de México y para Guadalajara y Monterrey). Mexico produce cerca del 40% del consumo del país e importa el resto principalmente desde Estados Unidos.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '12', 'content' => 'La refinería de Nicaragua es la única en Centroamérica que produce actualmente gasolina, cubriendo  el 37.3% de la demanda en 2022. El faltante se importaba anteriormente desde Venezuela quien desde 2016 fue desplazado por Estados Unidos. Existen dos gasolinas en el país, regular con un 31% de participación en el mercado y premium con un 69%.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '13', 'content' => 'En 2022 la gasolina regular (RON 91) representó el 28.3% del volumen consumido mientras que la premium (RON 95) alcanzaba un 71.7%. Se importa la totalidad de la gasolina  provenientes de Estados Unidos, Holanda y Alemania. '],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '14', 'content' => 'Para 2022, Perú superó los 800 millones de galones de gasolina (3,000 millones de litros). A partir de 2023, las gasolinas RON 84 y RON 90 se comercializarán como Gasolina Regular (RON 91) con el 70% de participación del mercado, y las gasolinas RON 95, RON 97 y RON 98 pasarán a ser Gasolina Premium (RON 96) con el 30% restante. La mayoría de sus gasolinas son producidas nacionalmente, llegando a importar entre el 10 y 15% de su demanda interna a países vecinos, Estados Unidos y Europa.'],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '15', 'content' => 'La demanda de gasolinas se cubre con la producción local que representa un 20% e importaciones provenientes de Estados Unidos, Trinidad y Tobago, Caribe, entre otros. En 2022, el consumo de gasolina regular fue  de 38.3%  del total nacional y el de premium de 61.7%. '],
            ['locale_id' => '4', 'key' => 'gasoline_demand', 'country_id' => '16', 'content' => 'En 2022, el consumo de gasolina fue de 233 millones de galones (880 millones de litros). La Gasolina Super con un RON 95 representó el 87% del total de la demanda, el resto fue Gasolina Premium con un RON 97. La producción de gasolinas en Uruguay alcanzó los 810 millones de litros y cubre casi la totalidad de la demanda.'],



            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '1', 'content' => 'La política sobre etanol es de ser autosuficientes en la producción y suministro de etanol para gasolinas. El requerimiento es variable en función de la producción nacional, actualmente es de 12% de etanol en gasolina.La producción iguala al consumo, habiendo pequeñas exportaciones a otros países.'],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '2', 'content' => 'El 80% es gasolina con etanol. Se comercializan E8 y E12 con etanol producido en el país en cinco empresas: Azúcar Aguaí, Unagro, Poplar Capital, Granosol,  y Guabirá.'],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '3', 'content' => 'Se permite el uso de hasta 5% de etanol,  pero no se utiliza actualmente. No produce o importa etanol.'],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '4', 'content' => 'Se permite la mezcla de etanol con gasolina en Colombia, permitido en 2010 con un 5% alcanzando actualmente un 10% de acuerdo con el Decreto 675 de 2015. El E10 es el grado predominante en el país excepto en frontera con Venezuela. El suministro de etanol proviene de importaciones de Estados Unidos y de producción local.'],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '5', 'content' => 'Se permite la mezcla de gasolina con hasta 10% de etanol desde 2010. El consumo de etanol es menos de 0.2%. En 2022 se produjeron 4.7 millones de litros y se exportaron 4.1 millones de litros principalmente a Europa. Se espera la introducción de E8 en 2024.'],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '6', 'content' => 'Hoy en día, la norma de calidad no especifica cuanto etanol debe mezclarse, mientras que se observa que las gasolinas ECOPAÍS y ECOPLUS son mezclas E5 y E8, respectivamente. La producción nacional de etanol satisface el consumo interno para su uso en combustibles, en otras industrias y en exportaciones a países vecinos.'],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '7', 'content' => 'En El Salvador no hay un mandato de etanol. Tiene potencial para producir etanol con base a maíz y azúcar.'],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '8', 'content' => 'Se permite hasta 10% de etanol en gasolina. Cuenta con producción de etanol avanzado que se exporta a Europa, pero no se mezcla en el país. Guatemala es el principal productor de etanol en Centroamérica. Se encuentra en aprobación mandato para E10 a partir de 2024.'],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '9', 'content' => 'En Honduras no hay un mandato de etanol. '],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '10', 'content' => 'En Jamaica, desde 2010, se obliga la mezcla de un 10% v/v de etanol en gasolina.  Anteriormente, se producía etanol localmente para Petrojam, sin embargo, actualmente se importa principalmente desde Estados Unidos.'],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '11', 'content' => 'Se permite el uso de etanol hasta 5.8% en todo el país, excepto en las Zonas Metropolitanas. El consumo actual de etanol equivale al 1.06% del consumo de gasolina Resto del País a nivel nacional. '],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '12', 'content' => 'En Nicaragua no existe mandato de etanol.'],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '13', 'content' => 'En 2011 se autorizó la mezcla con 2% v/v y un aumento gradual hasta alcanzar 20% v/v en 2016. Sin embargo, en 2013 se limitó a 5% v/v y en 2014 se dejó de utilizar por disputas políticas. Se espera la implementación de mandato de una mezcla obligatoria (iniciando en 5% en 2024 y llegando a 10% en 2026). '],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '14', 'content' => 'Se permiten gasolinas con etanol con 7.8% v/v . Perú produce etanol de caña de azucar para el mercado local y para exportaciones a paises vecinos. Adicionalmente se importa etanol  principalmente de Estados Unidos. '],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '15', 'content' => 'República Dominicana  no cuenta actualmente con mandato de etanol. '],
            ['locale_id' => '4', 'key' => 'ethanol_text', 'country_id' => '16', 'content' => 'En 2015 se permitió la mezcla de 5% v/v con un máximo permitido de 10% v/v. En Uruguay existen dos plantas de etanol, con una capacidad en conjunto de 100 millones de litros. La materia prima utilizada es caña de azúcar, sorgo, cebada, maíz y trigo.  En 2022, el consumo de etanol fue de  84 millones de litros.'],



            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '1', 'content' => 'Argentina’s total gasoline production is close to 2,500 million gallons per year (9,000 million liters per year), with a market share of approximately 75% as Nafta Súper / Grado 2 (RON 93 – AKI 87) and 80% as Nafta Ultra / Grado 3 (RON 97 – AKI 92). The demand for gasoline is a little higher than the supply, requiring imports of less than 250 million liters per year.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '2', 'content' => 'In 2022, gasoline demand was 526 million gallons (2,000 million liters). Gasoline Imports represented 38.4% of current demand,supplied from Brazil, Chile, Argentina, and the United States. Regular Gasoline (Especial) with 85 RON Octane represented 96% of demand and Premium Gasoline with a 95 RON octane the rest. In the short term, new intermediate octane gasolines will be available in the market.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '3', 'content' => 'Chile\'s gasoline consumption is currently over 1,400 millon gallons per year (5,000 million liters) in three grades: RON 93 (AKI 87), RON 95 (AKI 88) and RON 97 (AKI 92). There is a more stringent quality specification for Santiago Metropolitan Area. In 2022, the market share of RON 93 gasoline was 28%. Government company ENAP produces 80% of the total demand. Gasoline imports made in the country come mainly from Europe and the United States. Refineries only produce RON 93 and RON 97 gasoline, gasoline RON 95 is blended from these grades in gas stations.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '4', 'content' => 'In 2022,  gasoline consumption in Colombia was 1,800 million gallons (6,800 million liters). Market share was  3% for Extra gasoline E10 (RON 97 – AKI 94)  and 97% for Corriente gasoline (regular) E10 (RON  89 – AKI 84).  Local production supplies 65% of total demand.  United States is the mainly source of gasoline imports.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '5', 'content' => 'Costa Rica has two gasoline RON 95 and RON 91, with a market share of 51%  for RON 91 and 49% for RON 95 in 2022. As it does not have refining capacity, gasoline blends are made only with components imported mainly from the United States and to a lesser extent from Europe.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '6', 'content' => 'In 2022, gasoline consumption in Ecuador reached 1,200 millon galons (4,500 million liters). A new decree was stablished to implement new grades of gasoline: four grades with 5 different types: Gasoline Extra (RON 85), Gasoline Ecopais E10 (RON 85), Gasoline Ecoplus (RON 89), Gasoline Súper (RON 92) and Gasoline Súper Premium (RON 95). Gasoline Supere Premium (RON 95) will gradually substitute gasoline Super (RON 92). Gasoline Ecoplus (RON 89) was recently introuduced in the market. Ecuador has local production and imports naphtas (unfinished gasolines) to supply national demand. '],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '7', 'content' => 'In 2022, gasoline demand was 315 million galons (1,180 million liters). Regular gasoline RON 91 represented 50.6% of the volume consumed while Superior gasoline RON 95 reached 49.4%. Gasoline is supplied only by imports, distributed mainly by Chevron, Puma and Uno companies and imported mainly from the United States.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '8', 'content' => 'In 2022, gasoline consumption was 670 million galons ( 2,550 million liters). Gasoline is supplied only by imports, mainly from United States.  There are two grades of gasoline: (RON 91 - AKI 85) and Superior (RON 95 - AKI 89). 60% of gasoline is gasoline Regular. '],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '9', 'content' => 'In 2022, gasoline demand was 314 million gallons (1,190 million liters).  Regular gasoline RON 91 represented 44.6% while Superior gasoline RON 95 reached 55.6% of national demand. Honduras does not have gasoline production capacity, importing components for gasoline blending mainly from United States and to a lesser extent, from Ecuador.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '10', 'content' => 'In 2022, gasoline production was 476 million liters and gasoline imports 190 million liters, mainly from United States. Regular grade (AKI 87) had a market share of 36% and Premium grade (AKI 90) 64%.  Since 2010, only E10 has been consumed in Jamaica.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '11', 'content' => 'In 2022, gasoline consumption was 12,500 million gallons (20,000 million liters). There are two grades of gasoline, Regular (AKI 87) and Premium (AKI 91). Regular gasoline is the main grade in the market, representing 90%.  There are stringent gasoline specifications for major metropolitan areas in Mexico City, Guadalajara and Monterrey. Demand is much higher than production, making necessary to import 40% of gasoline mainly from the United States.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '12', 'content' => 'Nicaragua is the only country in Central America that has active refinery capacity, which produce 37.3% of gasoline national demand in 2022. The rest of demand is imported, previously from Venezuela and since 2016 mainly from United States. There are two gasoline grades in the country, regular with 31% and premium with 69% of market share.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '13', 'content' => 'In 2022, regular gasoline (RON 91) represented 28.3% of the volume consumed while premium gasoline (RON 95) reached 71.7%. Gasoline is supplied only with imports, mainly from United States, the Netherlands and Germany.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '14', 'content' => 'In 2022, Perú gasoline consumption surpassed 800 million gallons (3,000 millons liters). Starting in 2023, RON84 and RON 90 gasoline are commercialized  as Regular gasoline (RON 91)  with a 70% market participation. RON 95, RON 97 and RON 98 gasolines are now marketed as Premium gasoline (RON 96) with a 30% market share. La mayoría de sus gasolinas son producidas nacionalmente, llegando a importar entre el 10 y 15% de su demanda interna a países vecinos, Estados Unidos y Europa.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '15', 'content' => 'National demand is covered up by local production representing 20%, and imports from United States, Trinidad and Tobago, Caribbean, among other countries. In 2022, regular gasoline consumption was 38.3% of total demand and premium 61.7%.'],
            ['locale_id' => '2', 'key' => 'gasoline_demand', 'country_id' => '16', 'content' => 'In 2022, gasoline demand was 233 million galons (880 millon liters). Super Gasoline with RON 95 represented 87% of total demand and Premium Gasoline with RON 97 the rest.Gasoline production was 810 million liters and covers almost 100% of local demand.'],



            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '1', 'content' => 'Argentina\'s  policy is self-sufficiency and production and supply of ethanol for gasoline blend. Ethanol concentration varies according to local production.  Currently, the concentration limit is 12% v/v.  Ethanol production is almost equal to consumption. '],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '2', 'content' => '80% of gasoline demand contains ethanol. Gasoline E8 and E12 are currently marketed. All ethanol consumed in Bolivia is produced by five local companies: Azúcar Aguaí, Unagro, Poplar Capital, Granosol, and Guabirá.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '3', 'content' => 'Ethanol can be blended up to 5% v/v. However, ethanol is not used as a fuel or blended with gasoline.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '4', 'content' => 'Resolution 40391 of 2023 authorizes the blending of up to 7% ethanol in the country, but allows up to 10% in accordance with Decree 675 of 2015. E10 is the predominant grade in the country except on the border with Venezuela. The ethanol supply comes from imports from the United States and from local production.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '5', 'content' => 'Since 2010, it is allowed gasoline blends with up to 10% v/v of ethanol. However, this mandate is not yet reflected on the gasoline market. Current ethanol consumpition is less than 0.2%. In 2022, ethanol production was 4.7 million liters and ethanol exports mainly to Europe was 4.1 millon liters. Introduction of E8 is expected in 2024.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '6', 'content' => 'There is no specific mandate for ethanol blending, however there is a permit to blend it with gasoline. Therefore, E5 ECOPAIS and  E8 ECOPLUS are observed in the market since 2009. Ethanol is produced ,consumed and exported to neighbouring countries for fuel and industrial use. '],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '7', 'content' => 'El Salvador has no national specifications for ethanol. It has the potential to produce ethanol from maize and sugar cane.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '8', 'content' => 'Guatemala allows for blends up to 10% v/v but no ethanol is blended in the country. It has local ethanol advanced ethanol production that is  exported to Europe. Guatemala is the main ethanol productor in Central America. A E10 mandate for 2024 is currently under approval.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '9', 'content' => 'Honduras has no national mandate for ethanol blends.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '10', 'content' => 'E10 is mandate in Jamaica since 2010. Previously, ethanol was supplied with local production Petrojam, however, in recent years ethanol is mainly imported from the United States.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '11', 'content' => 'Blends with a maximum of 5.8% v/v of ethanol are allowed  with the exception of metropolitan regions of Valle de Mexico, Guadalajara and Monterrey. Current ethanol use is equivalent to an average of 1.06% in the Rest of the Country grade gasoline.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '12', 'content' => 'Nicaragua has no ethanol mandate.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '13', 'content' => 'In 2011, 2% v/v ethanol blends with gasoline were authorized, with a planned gradual increase until reaching 20% v/v by 2016. However, in 2013 it was limited to 5% v/v and by 2014 blending stopped because the only national producer announced its production cease due to political dispute. A new mandate implementation has been approved ( starting with E5 in 2024  and reaching E10 in 2026). '],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '14', 'content' => 'Blends with 7.8% v/v are allowed. Peru produces ethanol from sugarcane; however, its destination is mainly the EU market. Ethanol imports from the United States and to a lesser degree from Brazil are used for the national blend.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '15', 'content' => 'Dominican Republic does not currently have an ethanol mandate.'],
            ['locale_id' => '2', 'key' => 'ethanol_text', 'country_id' => '16', 'content' => 'Since 2015, 5% v/v blends with a maximum limit of 10% v/v were allowed. In Uruguay there are two ethanol plants with an overall capacity of 100 million liters per year, raw material commonly used are sugar cane, sorghum, barley, corn, and wheat. In 2022, ethanol consumption was 22 million gallons (84 million liters).'],

        ]);
    }
}
