<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class LatamDynamicToolText extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {

        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '1', 'key' => 'gasoline_demand'])->update(['content' => 'La demanda total de gasolina de Argentina fue de 2.408 millones de galones en 2025 (9.117 millones de litros), con una distribución de mercado de 74,2% como Nafta Súper / Grado 2 (RON 93 min – AKI 87) y del 25,8% como Nafta Ultra / Grado 3 (RON 97 min – AKI 92). El octano entregado al mercado suele ser superior al mínimo requerido. La demanda de gasolina se supone principalmente por la producción local, lo que requiere importaciones de menos de 75 millones de litros de media anual.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '2', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, la demanda de gasolina fue de 606 millones de galones (2.295 millones de litros). Las importaciones de gasolina representaban el 52% de la demanda y se suministran desde Brasil, Chile, Argentina y Estados Unidos. La gasolina normal (Special) con 85 RON de octanaje representaba el 90% de la demanda y la gasolina con 95 RON o más de octanos, el 10% restante. La producción de gasolina ha disminuido en los últimos años.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '3', 'key' => 'gasoline_demand'])->update(['content' => 'El consumo de gasolina en Chile supera actualmente los 1,180 millones de galones al año (4,460 millones de litros) distribuidos en tres grados: RON 93 (AKI 87), RON 95 (AKI 88) y RON 97 (AKI 92). Existe una especificación de calidad más estricta para el Área Metropolitana de Santiago. En 2025, la distribución de mercado de la gasolina RON 93 fue del 62%. La empresa gubernamental ENAP produce el 77% de la demanda total (CNE). Las importaciones de gasolina realizadas en el país provienen principalmente de Estados Unidos. Las refinerías solo producen RON 93 y RON 97, y la gasolina RON 95 se mezcla a partir de estas categorías en gasolineras.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '4', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, el consumo de gasolina en Colombia fue de 2.184 millones de galones (8.270 millones de litros). La distribución de mercado fue del 3% para la gasolina extra E10 (RON 97 – AKI 94) y el 97% restante para la gasolina regular (regular) E10 (RON 89 – AKI 84). La producción local suministra el 43% de la demanda total. Estados Unidos es la principal fuente de importaciones de gasolina.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '5', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, la demanda de gasolina fue de 387 millones de galones (1468 millones de litros). Costa Rica tiene dos grados de gasolina: RON 95 y RON 91, con una cuota de mercado del 41% para RON 91 y 59% para RON 95. La refinería de Limón cesó su producción en 2012. El suministro de gasolina se realiza principalmente con importaciones de Estados Unidos y parte de Europa.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '6', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, el consumo de gasolina en Ecuador fue de 1,205 millones de galones (4,561 millones de litros). Se estableció un nuevo plan para implementar nuevos grados de gasolina: cuatro grados con 5 tipos diferentes según la norma de calidad actual (NTE INEN 935:2021): Extra (RON 85), Ecopais E10 (RON 85), Ecoplus (RON 89), Súper (RON 92) y Super Premium (RON 95). Super Premium (RON 95) irá sustituyendo gradualmente a Super (RON 92). Gasolina Ecoplus (RON 89) se introdujo recientemente en el mercado. Ecuador tiene producción local e importa nafta (gasolina inacabada) para satisfacer la demanda nacional.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '7', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, la demanda de gasolina fue de 328 millones de galones (1,241 millones de litros). La gasolina regular RON 91 representaba el 51% del volumen consumido, mientras que la gasolina Superior RON 95 alcanzaba el 49%. La gasolina se suministra únicamente por importación, distribuida principalmente por las compañías Chevron, Puma y Uno e importada principalmente desde Estados Unidos.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '8', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, el consumo de gasolina fue de 824 millones de galones (3,119 millones de litros). La gasolina se suministra únicamente por importaciones, principalmente de Estados Unidos. Existen dos grados de gasolina: (RON 91 - AKI 85) y Superior (RON 95 - AKI 89). El 53% de la gasolina es gasolina normal.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '9', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, la demanda de gasolina fue de 385 millones de galones (1,457 millones de litros). La gasolina regular RON 91 representó el 44%, mientras que la gasolina Superior RON 95 alcanzó el 56% de la demanda nacional. Honduras no dispone de capacidad para producir gasolina y abastece su mercado principalmente de importaciones de Estados Unidos.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '10', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, la demanda de gasolina fue de 206 millones de galones (779 millones de litros). La producción de gasolina fue de 34 millones de galones (130 millones de litros) y las importaciones de 195 millones de galones (739 millones de litros) principalmente de Estados Unidos. La versión regular (AKI 87) tenía una distribución de mercado del 35% y la Premium grade (AKI 90) del 65%.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '11', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, el consumo de gasolina fue de 12,447 millones de galones (47,116 millones de litros). Existen dos categorías de gasolina, Regular (AKI 87) y Premium (AKI 91). La gasolina regular es la principal categoría del mercado, representando el 80% del volumen. Existen especificaciones estrictas de gasolina para las principales áreas metropolitanas de Ciudad de México, Guadalajara y Monterrey. La demanda es mucho mayor que la producción, por lo que es necesario importar el 40% de la gasolina, principalmente de Estados Unidos.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '12', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, la demanda de gasolina fue de 151 millones de galones (574 millones de litros). Nicaragua es el único país de Centroamérica que cuenta con capacidad activa de refinería, que produjo el 38% de la demanda nacional de gasolina. El resto de la demanda se importa, anteriormente de Venezuela y desde 2016 principalmente de Estados Unidos. Hay dos categorías de gasolina en el país: regular con un 30% y premium con un 70% de cuota de mercado.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '13', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025 la demanda fue de 363 millones de galones (1374 millones de litros). La gasolina normal (RON 91) representaba el 33% de la demanda total y la gasolina Superior (RON 95) el 67%. La gasolina se suministra únicamente con importaciones, principalmente de Estados Unidos, Países Bajos y Alemania.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '14', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, el consumo de gasolina en Perú es de 897 millones de galones (3,397 millones de litros). A partir de 2023 se implementó un programa para aumentar el octano en la gasolina; La gasolina RON 84 y RON 90 se comercializan como gasolina regular (RON 91) con una participación en el mercado del 42%. Las gasolinas RON 95, RON 97 y RON 98 se comercializan ahora como gasolina Premium (RON 96) con una cuota de mercado del 58%. La gasolina con etanol (gasohol) debe cumplir con un número adicional de octano (RON 91 y RON 96 respectivamente). El suministro local de gasolina se realiza con la producción de Petroperú, Repsol y Primax. Las importaciones de gasolina representan entre el 10 y el 15% de la demanda, y son suministradas por mercados locales, Estados Unidos y Europa.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '15', 'key' => 'gasoline_demand'])->update(['content' => 'La demanda nacional está cubierta por la producción local que representa el 12%, y por importaciones de Estados Unidos, Trinidad y Tobago, el Caribe, entre otros países. En 2025, el consumo de gasolina fue de 581 millones de galones (2,200 millones de litros). El consumo regular de gasolina representaba el 32% de la demanda total y la prima el 68%. El Gobierno dominicano aplica subsidios a los precios de la gasolina.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '16', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025, la demanda de gasolina fue de 254 millones de galones (960 millones de litros). Super Gasolina con RON 95 representaba el 83% de la demanda total y Gasolina Premium con RON 97 el resto. La producción de gasolina fue de 210 millones de galones (casi 800 millones de litros) y cubre el 83% de la demanda local.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '1', 'key' => 'ethanol_text'])->update(['content' => 'La política argentina es la autosuficiencia y la producción y suministro de etanol para mezclas de gasolina. La concentración de etanol varía según la producción local.  Actualmente, el límite de concentración es del 15% v/v. (Resolución 2026-79-APN-SE#MEC). La producción de etanol es igual al consumo con algunas exportaciones e importaciones de otros países.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '2', 'key' => 'ethanol_text'])->update(['content' => 'Actualmente se comercializan las gasolinas E8 y E12 (Decreto Supremo No. 4718:ANH), pero recientemente se aprobaron mezclas del 25%. Aproximadamente el 80% de la demanda de gasolina contiene etanol. Todo el etanol consumido en Bolivia es producido por cinco empresas locales: Azúcar Aguaí, Unagro, Poplar Capital, Granosol y Guabirá.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '3', 'key' => 'ethanol_text'])->update(['content' => 'El etanol puede mezclarse hasta un 5% v/v (Decreto Supremo 56), pero no se utiliza debido a barreras regulatorias. Chile no produce ni importa etanol. Se está analizando el uso del etanol para alcanzar objetivos a corto plazo en el programa nacional de descarbonización de la economía.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '4', 'key' => 'ethanol_text'])->update(['content' => 'Las mezclas de etanol son obligatorias en ciudades con más de 500.000 habitantes. La resolución 40444 de 2023 autoriza la mezcla de hasta un 10% de etanol en el país y permite porcentajes más bajos en casos concretos. E10 es el grado predominante en el país, excepto en la frontera con Venezuela. El suministro de etanol proviene de importaciones de Estados Unidos y de la producción local.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '5', 'key' => 'ethanol_text'])->update(['content' => 'Se permiten mezclas de gasolina con hasta un 10% v/v de etanol (INTE E1:2019). Sin embargo, este mandato aún no se refleja en el mercado de la gasolina. El consumo actual de etanol es inferior al 0,2% porque no existe consenso entre los interesados para la implementación. En 2025, la producción de etanol fue de 7,5 millones de galones (28,2 millones de litros) y las exportaciones de etanol, principalmente a Europa, fueron de casi 6 millones de galones (22,5 millones de litros). Se espera la introducción de la E10 por parte del Gobierno en 2026.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '6', 'key' => 'ethanol_text'])->update(['content' => 'No existe un mandato específico para la mezcla de etanol, pero sí existe un permiso para mezclarlo con gasolina. El etanol se mezcla con gasolina desde 2009. Hoy en día, la mezcla habitual es E10 para Ecoplus y Super. La gasolina Ecopais se suministra en algunas provincias con un contenido de etanol entre el 3 y el 4%. Se produce, consume y exporta etanol a países vecinos para uso de combustible e industria.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '7', 'key' => 'ethanol_text'])->update(['content' => 'El Salvador no tiene un mandato nacional para el etanol. Tiene el potencial de producir etanol a partir del maíz y la caña de azúcar. En el último año ha habido interés por su uso.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '8', 'key' => 'ethanol_text'])->update(['content' => 'Guatemala aprobó el mandato para las mezclas E10 en todo el territorio en 2025. Cuenta con una producción local avanzada de etanol que se exporta a Europa. Guatemala es el principal productor de etanol en Centroamérica.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '9', 'key' => 'ethanol_text'])->update(['content' => 'Honduras no tiene un mandato nacional para las mezclas de etanol. Se está discutiendo una nueva ley sobre biocombustibles.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '10', 'key' => 'ethanol_text'])->update(['content' => 'La norma actual de calidad de gasolina exige la norma E10 (JS 341:2017). Anteriormente, el etanol se suministraba con producción local a Petrojam, sin embargo, en los últimos años se importa etanol desde Estados Unidos.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '11', 'key' => 'ethanol_text'])->update(['content' => 'La norma de calidad de la gasolina (NOM-016-CRE de 2016) permite mezclas con un máximo de 5,8% v/v de etanol, con la excepción de las áreas metropolitanas del Valle de México, Guadalajara y Monterrey. El uso actual de etanol equivale a una media del 1,06% en la gasolina de grado Rest of the Country. En 2025 se aprobó una nueva ley de biocombustibles que fomenta la producción con residuos agrícolas y otros productos orgánicos. Recientemente hay nuevos esfuerzos a nivel estatal para aumentar el consumo de etanol (por ejemplo, Tamaulipas).']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '12', 'key' => 'ethanol_text'])->update(['content' => 'Según el Ministerio de Energía y la RTCA, Nicaragua no tiene mandato para el etanol.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '13', 'key' => 'ethanol_text'])->update(['content' => 'En 2011, se autorizaron mezclas de etanol al 2% v/v con gasolina, con un aumento gradual previsto hasta alcanzar el 10% v/v en 2016. Sin embargo, en 2013 se limitó al 5% v/v y para 2014 la mezcla se detuvo porque el único productor nacional anunció el cese de su producción debido a disputas políticas. Se ha aprobado una nueva implementación del mandato para E10 y se espera que se implemente entre 2026 y 2027.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '14', 'key' => 'ethanol_text'])->update(['content' => 'Se permiten mezclas con 7,8% v/v (Decreto Supremo N.° 021-2007-EM: MINEM). Perú produce etanol a partir de caña de azúcar; sin embargo, su destino es principalmente el mercado de la UE. Las importaciones de etanol desde Estados Unidos y, en menor medida, de Brasil se utilizan para la mezcla nacional.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '15', 'key' => 'ethanol_text'])->update(['content' => 'Actualmente, la República Dominicana no tiene un mandato sobre el etanol.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '4', 'country_id' => '16', 'key' => 'ethanol_text'])->update(['content' => 'Se permiten mezclas de gasolina con hasta un 10% de v/v. En Uruguay hay dos plantas de etanol con una capacidad total de 100 millones de litros al año; las materias primas más utilizadas son la caña de azúcar, el sorgo y el maíz. En 2025, el consumo de etanol fue de 25 millones de galones (94 millones de litros).']);


        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '1', 'key' => 'gasoline_demand'])->update(['content' => 'Argentina’s total gasoline demand was 2,408 million gallons in 2025 (9,117 million liters), with a market share of approximately 74.2% as Nafta Súper / Grado 2 (RON 93 min  – AKI 87) and 25.8% as Nafta Ultra / Grado 3 (RON 97 min – AKI 92). Octane delivered to market is usually higher than the minimum required. The demand for gasoline is supplied mostly by local production, requiring imports of less than 75 million liters per year average.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '2', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, gasoline demand was 606 million gallons (2,295 million liters). Gasoline Imports represented 52% of demand, and are supplied from Brazil, Chile, Argentina, and the United States. Regular Gasoline (Especial) with 85 RON Octane represented 90% of demand and the Gasoline with a 95 RON or more octane, the remaining 10%. Gasoline production has decreased in the last years.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '3', 'key' => 'gasoline_demand'])->update(['content' => 'Chile\'s gasoline consumption is currently over 1,180 million gallons per year (4,460 million liters) distributed  in three grades: RON 93 (AKI 87), RON 95 (AKI 88) and RON 97 (AKI 92). There is a more stringent quality specification for Santiago Metropolitan Area. In 2025, the market share of RON 93 gasoline was 62%. Government company ENAP produces 77% of the total demand (CNE). Gasoline imports made in the country come mainly from the United States. Refineries only produce RON 93 and RON 97, gasoline RON 95 is blended from these grades in gas stations.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '4', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025,  gasoline consumption in Colombia was 2,184 million gallons (8,270 million liters). Market share was 3% for Extra gasoline E10 (RON 97 – AKI 94) and remaining 97% for Regular gasoline (regular) E10 (RON 89 – AKI 84). Local production supplies 43% of total demand. United States is the main source of gasoline imports.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '5', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, gasoline demand was 387 million gallons (1468 million liters). Costa Rica has two grades of gasoline RON 95 and RON 91, with a market share of 41% for RON 91 and 59% for RON 95. The Limon refinery stopped production in 2012. Gasoline supply is done with imports mainly from the United States and some from Europe. ']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '6', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, gasoline consumption in Ecuador was 1,205 million gallons (4,561 million liters). A new plan was stablished to implement new grades of gasoline: four grades with 5 different types according to the current quality norm (NTE INEN 935:2021): Extra (RON 85), Ecopais E10 (RON 85), Ecoplus (RON 89), Súper (RON 92) and Super Premium (RON 95). Super Premium (RON 95) will gradually substitute Super (RON 92). Gasoline Ecoplus (RON 89) was recently introduced in the market. Ecuador has local production and imports naphtha (unfinished gasolines) to supply national demand.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '7', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, gasoline demand was 328 million gallons (1,241 million liters). Regular gasoline RON 91 represented 51% of the volume consumed while Superior gasoline RON 95 reached 49%. Gasoline is supplied only by imports, distributed mainly by Chevron, Puma and Uno companies and imported mainly from the United States.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '8', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, gasoline consumption was 824 million gallons (3,119 million liters). Gasoline is supplied only by imports, mainly from United States. There are two grades of gasoline: (RON 91 - AKI 85) and Superior (RON 95 - AKI 89). 53% of gasoline is gasoline Regular.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '9', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, gasoline demand was 385 million gallons (1,457 million liters). Regular gasoline RON 91 represented 44% while Superior gasoline RON 95 reached 56% of national demand. Honduras does not have gasoline production capacity and supplies its market with imports mainly from the United States.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '10', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, gasoline demand was 206 million gallons (779 million liters). Gasoline production was 34 million gallons (130 million liters) and imports 195 million gallons (739 million liters) mainly from United States. Regular grade (AKI 87) had a market share of 35% and Premium grade (AKI 90) 65%.  ']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '11', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, gasoline consumption was 12,447 million gallons (47,116 million liters). There are two grades of gasoline, Regular (AKI 87) and Premium (AKI 91). Regular gasoline is the main grade in the market, representing 80% of the volume. There are stringent gasoline specifications for major metropolitan areas in Mexico City, Guadalajara and Monterrey. Demand is much higher than production, making necessary to import 40% of gasoline mainly from the United States.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '12', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, gasoline demand was 151 million gallons (574 million liters). Nicaragua is the only country in Central America that has active refinery capacity, which produced 38% of gasoline national demand. The rest of demand is imported, previously from Venezuela and since 2016 mainly from United States. There are two gasoline grades in the country, regular with 30% and premium with 70% of market share.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '13', 'key' => 'gasoline_demand'])->update(['content' => 'En 2025 demand was 363 million gallons (1374 million liters). Regular gasoline (RON 91) represented 33% of total demand and Superior gasoline (RON 95) 67%. Gasoline is supplied only with imports, mainly from United States, the Netherlands and Germany.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '14', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, Peru gasoline consumption is 897 million gallons (3,397 millions liters). Starting in 2023 a program to increase octane in gasoline was implemented; RON 84 and RON 90 gasoline are commercialized  as Regular gasoline (RON 91)  with a 42% market participation. RON 95, RON 97 and RON 98 gasolines are now marketed as Premium gasoline (RON 96) with a 58% market share. Gasoline with ethanol (gasohol) is required to meet one additional octane number (RON 91 and RON 96 respectively). Local gasoline supply is done with production from Petroperú, Repsol and Primax. Gasoline imports account for 10 to 15% of demand, and are supplied by local markets, United states  and Europe.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '15', 'key' => 'gasoline_demand'])->update(['content' => 'National demand is covered up by local production representing 12%, and imports from United States, Trinidad and Tobago, Caribbean, among other countries. In 2025, gasoline consumption was 581 million gallons (2,200 million liters). Regular gasoline consumption was 32% of total demand and premium 68%. The Dominican Government applies subsidies to gasoline prices.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '16', 'key' => 'gasoline_demand'])->update(['content' => 'In 2025, gasoline demand was 254 million gallons (960 million liters). Super Gasoline with RON 95 represented 83% of total demand and Premium Gasoline with RON 97 the rest. Gasoline production was 210 millions gallons (almost 800 millions liters) and covers 83% of local demand.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '1', 'key' => 'ethanol_text'])->update(['content' => 'Argentina\'s policy is self-sufficiency and production and supply of ethanol for gasoline blend. Ethanol concentration varies according to local production.  Currently, the concentration limit is 15% v/v. (Resolution 2026-79-APN-SE#MEC). Ethanol production is equal to consumption with some exports and imports from other countries.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '2', 'key' => 'ethanol_text'])->update(['content' => 'Gasoline E8 and E12 are currently marketed (Decreto Supremo No. 4718:ANH), but recently was approved blends of 25%. About 80% of gasoline demand contains ethanol. All ethanol consumed in Bolivia is produced by five local companies: Azúcar Aguaí, Unagro, Poplar Capital, Granosol, and Guabirá.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '3', 'key' => 'ethanol_text'])->update(['content' => 'Ethanol can be blended up to 5% v/v (Decreto Supremo 56) but it is not used because of regulatory barriers. Chile does not produce or imports ethanol. The use of ethanol is being analyzed to achieve short term goals in the national economy decarbonization program.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '4', 'key' => 'ethanol_text'])->update(['content' => 'Ethanol blends are obligatory in cities with more than 500,000 habitants. Resolution 40444 of 2023 authorizes the blending of up to 10% ethanol in the country and allows for lower percentages in particular cases. E10 is the predominant grade in the country except on the border with Venezuela. The ethanol supply comes from imports from the United States and from local production.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '5', 'key' => 'ethanol_text'])->update(['content' => 'Gasoline blends with up to 10% v/v of ethanol are allowed (INTE E1:2019). However, this mandate is not yet reflected on the gasoline market. Current ethanol consumption is less than 0.2% because there is no stakeholder’s consensus for implementation. In 2025, ethanol production was 7.5  million gallons (28.2 million liters) and ethanol exports mainly to Europe was almost  6 million gallons (22.5 million liters). Introduction of E10 is expected by the Government in 2026.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '6', 'key' => 'ethanol_text'])->update(['content' => 'There is no specific mandate for ethanol blending, however there is a permit to blend it with gasoline. Ethanol has been blending in gasoline since 2009. Today the usual blend is E10 for Ecoplus and Super. Ecopais gasoline is supplied in some provinces with an ethanol content  between 3-4%. Gasoline Ethanol is produced ,consumed and exported to neighboring countries for fuel and industrial use.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '7', 'key' => 'ethanol_text'])->update(['content' => 'El Salvador has no national mandate for ethanol. It has the potential to produce ethanol from maize and sugar cane. In the last year there has been an interest for its use.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '8', 'key' => 'ethanol_text'])->update(['content' => 'Guatemala approved the mandate for E10 blends throughout the territory in 2025. It has local ethanol advanced ethanol production that is exported to Europe. Guatemala is the main ethanol productor in Central America. ']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '9', 'key' => 'ethanol_text'])->update(['content' => 'Honduras has no national mandate for ethanol blends. A new biofuel’s law is under discussion.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '10', 'key' => 'ethanol_text'])->update(['content' => 'Current gasoline quality norm mandates E10 (JS 341:2017) . Previously, ethanol was supplied with local production to Petrojam, however, in recent years, ethanol is imported from the United States.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '11', 'key' => 'ethanol_text'])->update(['content' => 'Gasoline quality norm (NOM-016-CRE de 2016) allows blends with a maximum of 5.8% v/v of ethanol  with the exception of metropolitan areas of Valle de Mexico, Guadalajara and Monterrey. Current ethanol use is equivalent to an average of 1.06% in the Rest of the Country grade gasoline. In 2025, a new biofuels law was approved that fosters the production with agricultural and other organic residuals. Recently there are new state level efforts to increase ethanol consumption (e.g. Tamaulipas).']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '12', 'key' => 'ethanol_text'])->update(['content' => 'According to the Ministry of Energy and RTCA, Nicaragua has no ethanol mandate.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '13', 'key' => 'ethanol_text'])->update(['content' => 'In 2011, 2% v/v ethanol blends with gasoline were authorized, with a planned gradual increase until reaching 10% v/v by 2016. However, in 2013 it was limited to 5% v/v and by 2014 blending stopped because the only national producer announced its production cease due to political dispute. A new mandate implementation has been approved for E10  and is  expected  to be implemented between 2026 and 2027.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '14', 'key' => 'ethanol_text'])->update(['content' => 'Blends with 7.8% v/v are allowed (Decreto Supremo N.° 021-2007-EM: MINEM). Peru produces ethanol from sugarcane; however, its destination is mainly the EU market. Ethanol imports from the United States and to a lesser degree from Brazil are used for the national blend.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '15', 'key' => 'ethanol_text'])->update(['content' => 'Dominican Republic does not currently have an ethanol mandate.']);
        DB::table('dynamic_tools_texts')->where(['locale_id' => '2', 'country_id' => '16', 'key' => 'ethanol_text'])->update(['content' => 'Gasoline Blends with up to 10% v/v  are allowed. In Uruguay there are two ethanol plants with an overall capacity of 100 million liters per year, raw material commonly used are sugar cane, sorghum, and corn. In 2025, ethanol consumption was 25 million gallons (94 million liters).']);





        DB::table('dynamic_tools_texts')->insert([
            
            ['locale_id' => '2', 'country_id' => '27', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Austria was 1,999 million liters (528 million gallons) and growth rate was -0.5%. Gasoline production and net imports were 2,264 and -273 million liters (598 and -72 million gallons) respectively. Austria complies with the European gasoline standards and offers two main grades: (RON 95 and RON 98) with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '28', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Belgium was 3,761 million liters (993 million gallons) and growth rate was 6.2%. Gasoline production and net imports were 4,397 and -4,172 million liters (1,162 and -1,102 million gallons) correspondingly. Belgium complies with the European gasoline standards and offers two main grades: RON 95 and RON 98) with an average octane of 95.3 RON.'],
            ['locale_id' => '2', 'country_id' => '29', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Bulgaria was 885 million liters (234 million gallons) and growth rate was  0.79%. Gasoline production and net imports were 1,664 and -735 million liters (440 and -194 million gallons) correspondingly. Bulgaria complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '30', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Croatia was 772 million liters (204 million gallons) and growth rate was  -0.8%. Gasoline production and net imports were 1,310 and -510 million liters (346 and -135 million gallons) correspondingly. Croatia complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.3 RON.'],
            ['locale_id' => '2', 'country_id' => '31', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Cyprus was 465 million liters (123 million gallons) and growth rate was  -0.74%. Gasoline production and net imports were 0 and 481 million liters (0 and 127 million gallons) correspondingly. Cyprus complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.3 RON.'],
            ['locale_id' => '2', 'country_id' => '32', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Czechia was 2,445 million liters (646 million gallons) and growth rate was  -0.19%. Gasoline production and net imports were 2,033 and 214 million liters (537 and 56 million gallons) correspondingly. Czechia complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.1 RON.'],
            ['locale_id' => '2', 'country_id' => '33', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Denmark was 1,576 million liters (416 million gallons) and growth rate was  -1.3%. Gasoline production and net imports were 2,633 and -1,062 million liters (696 and -280 million gallons) correspondingly. Denmark complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.3 RON.'],
            ['locale_id' => '2', 'country_id' => '34', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Estonia was 286 million liters (76 million gallons) and growth rate was  -1.9%. There is no gasoline production. Gasoline net imports were 341 million liters (90 million gallons). Estonia complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 96.1 RON.'],
            ['locale_id' => '2', 'country_id' => '35', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Finland was 1,723 million liters (455 million gallons) and growth rate was  -1.3%. Gasoline production and net imports were 5,696 and -3,919 million liters (1,505 and -1,035 million gallons) correspondingly. Finland complies with the European gasoline standards and offers two main grades: RON 95 and RON 98) with an average octane of 95.6 RON.'],
            ['locale_id' => '2', 'country_id' => '36', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in France was 14,702 million liters (3,884 million gallons) and growth rate was 1.5%. Gasoline production and net imports were 11,926 and 1,072 million liters (3,150 and 283 million gallons) correspondingly. France complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.7 RON.'],
            ['locale_id' => '2', 'country_id' => '37', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Germany was 23,067 million liters (6,093 million gallons) and growth rate was  0.23%. Gasoline production and net imports were 25,530 and -2,754 million liters (6,744 and -727 million gallons) correspondingly. Germany complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '38', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Greece was 3,156 million liters (834 million gallons) and growth rate was  -2.8%. Gasoline production and net imports were 7,983 and -6041 million liters (2,109 and -1,596 million gallons) correspondingly. Greece complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.5 RON.'],
            ['locale_id' => '2', 'country_id' => '39', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Hungary was 1,908 million liters (504 million gallons) and growth rate was  2.2%. Gasoline production and net imports were 1,438 and 473 million liters (380 and 125 million gallons) correspondingly. Hungary complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.4 RON.	'],
            ['locale_id' => '2', 'country_id' => '40', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Ireland was 1,122 million liters (296 million gallons) and growth rate was  -3.3%. Gasoline production and net imports were 721 and 246 million liters (191 and 65 million gallons) correspondingly. Ireland complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.3 RON.'],
            ['locale_id' => '2', 'country_id' => '41', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Italy was 11,871 million liters (3,136 million gallons) and growth rate was  3.2%. Gasoline production and net imports were 17,503 and -5,636 million liters (4,624 and -1,489 million gallons) correspondingly. Italy complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '42', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Latvia was 227 million liters (60 million gallons) and growth rate was  -3.3%. There is no gasoline production. Gasoline net imports were 123 million liters (33 million gallons). Latvia complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.3 RON.'],
            ['locale_id' => '2', 'country_id' => '43', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Lithuania was 479 million liters (127 million gallons) and growth rate was  1.4%. Gasoline production and net imports were 4,056 and -3,577 million liters (1,071 and -944 million gallons) correspondingly. Lithuania complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.3 RON.'],
            ['locale_id' => '2', 'country_id' => '44', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Luxembourg was 539 million liters (142 million gallons) and growth rate was 0.86%. There is no gasoline production. Gasoline net imports were 485 million liters (128 million gallons) correspondingly. Luxembourg complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.6 RON.	'],
            ['locale_id' => '2', 'country_id' => '45', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Malta was 122 million liters (32 million gallons) and growth rate was  1.5%. There is no gasoline production. Gasoline imports were  and 74 million liters (20 million gallons) . Malta complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.0 RON.'],
            ['locale_id' => '2', 'country_id' => '46', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Netherlands was 4,514 million liters (1,192 million gallons) and growth rate was  -0.28%. Gasoline production and net imports were 18,087 and -13,573 million liters (4,778 and -3,586 million gallons) correspondingly. Netherlands complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.1 RON.'],
            ['locale_id' => '2', 'country_id' => '47', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Poland was 8,220 million liters (2,172 million gallons) and growth rate was  3.31%. Gasoline production and net imports were 6,532 and 1,599 million liters (1,726 and 422 million gallons) correspondingly. Poland complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '48', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Portugal was 1,797 million liters (475 million gallons) and growth rate was - 0.3%. Gasoline production and net imports were 2,464 and -667 million liters (651 and -176 million gallons) correspondingly. Portugal complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '49', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Romania was 1,948 million liters (515 million gallons) and growth rate was  -0.3%. Gasoline production and net imports were 4,115 and -2,167 million liters (1,087 and -573 million gallons) correspondingly. Romania complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '50', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Slovakia was 852 million liters (225 million gallons) and growth rate was  0.1%. Gasoline production and net imports were 1,887 and -1,035 million liters (498 and -273 million gallons) correspondingly. Slovakia complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '51', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Slovenia was 572 million liters (151 million gallons) and growth rate was  -1.8%. Gasoline production and net imports were 0 and 572 million liters (0 and 151 million gallons) correspondingly. Slovenia complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '52', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Spain was 8,903 million liters (2,352 million gallons) and growth rate was  1.4%. Gasoline production and net imports were 10,808 and -1,906 million liters (2,855 and -503 million gallons) correspondingly. Spain complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '53', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in Sweden was 2,688 million liters (710 million gallons) and growth rate was  -3.5%. Gasoline production and net imports were 6,801 and -4,113 million liters (1,797 and -1,087 million gallons) correspondingly. Sweden complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '54', 'key' => 'gasoline_demand', 'content' => 'In 2025, gasoline consumption in United Kingdom was 14,873 million liters (3,929 million gallons) and growth rate was  -1.2%. Gasoline production and net imports were 19,506 and -4,633 million liters (5,152 and -1,224 million gallons) correspondingly. United Kingdom complies with the European gasoline standards and offers two main grades: RON 95 and RON 98 with an average octane of 95.2 RON.'],
            ['locale_id' => '2', 'country_id' => '27', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Austria was 204 million liters (54 million gallons) representing  10.% of gasoline demand. Ethanol production and Net Imports were 216 and -15 million liters (57  and -4 million gallons) correspondingly. Ethanol sources are Sugar Cane%,Corn 75%, Cereals 15%, Sugar Beet 10%.'],
            ['locale_id' => '2', 'country_id' => '28', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Belgium was 165 million liters (43 million gallons) representing  4% of gasoline demand. Ethanol production and Net Imports were 620 and  -105 million liters (164  and -28 million gallons) correspondingly. Ethanol sources are Sugar Cane 20% and Cereals 80%.'],
            ['locale_id' => '2', 'country_id' => '29', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Bulgaria was 54 million liters (14 million gallons) representing  6% of gasoline demand. Ethanol Net Imports were 15 million liters each (4 million gallons). Ethanol sources are Corn 45% and Cereals 55%.'],
            ['locale_id' => '2', 'country_id' => '30', 'key' => 'ethanol_text', 'content' => 'Altough E10 is allowed in Croatia, it does not produce or consumes bioethanol in a commercial level. There is a small production of generic ethanol that is exported in minimal quantities to Italy, Slovenia, Austria and Bosnia.'],
            ['locale_id' => '2', 'country_id' => '31', 'key' => 'ethanol_text', 'content' => 'Cyprus has no specific ethanol mandate and a target of 14% biofuels in the transport sector by 2030. Ethanol demand was 19.2 million liters in 2025 (5.1 million gallons) equivalent to 4.1% of gasoline demand. Ethanol is supplied by imports.'],
            ['locale_id' => '2', 'country_id' => '32', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Czechia was 227 million liters (60 million gallons) representing  10% of gasoline demand. Ethanol production and Net Imports were 47 and  123 million liters (12  and 32 million gallons) correspondingly. Ethanol sources are Corn 50% and Sugar Beet 50%.'],
            ['locale_id' => '2', 'country_id' => '33', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Denmark was 242 million liters (64 million gallons) representing  18% of gasoline demand. Ethanol production and Net Imports were 206 and 270  million liters (54  and 72 million gallons) correspondingly.'],
            ['locale_id' => '2', 'country_id' => '34', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Estonia was 5 million liters (1 million gallons) representing  2% of gasoline demand. Ethanol imports were 5 million liters (1 million gallons). Ethanol sources is Cereals 100%.'],
            ['locale_id' => '2', 'country_id' => '35', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Finland was 155 million liters (41 million gallons) representing  9% of gasoline demand. Ethanol production and Net Imports were 23 and 87 million liters (6 and 23 million gallons) correspondingly. Ethanol sources are Corn 5%, Cereals 85% and 2G lignocelulosic Ethanol 10%.'],
            ['locale_id' => '2', 'country_id' => '36', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in France was 1,518 million liters (401 million gallons) representing  10% of gasoline demand. Ethanol production and Net Imports were 1,192 and 325 million liters (315  and 86 million gallons) correspondingly. Ethanol sources are Corn 32%, Cereals 21% and Sugar Beet 47%.'],
            ['locale_id' => '2', 'country_id' => '37', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Germany was 1,548 million liters (409 million gallons) representing  7% of gasoline demand. Ethanol production and Net Imports were 1,001 and 547 million liters (265  and 145 million gallons) correspondingly. Ethanol sources are Wheat 47%,  Sugar Beet 20%, Corn 11% and Other Cereals 21%.'],
            ['locale_id' => '2', 'country_id' => '38', 'key' => 'ethanol_text', 'content' => 'Ethanol consumption in Greece is determined by 3.3% bioethanol content mandate (by energy). In 2025 demand was 164 million liters (43 million gallons) representing  5.0% of gasoline demand. Ethanol is supplied by imports. '],
            ['locale_id' => '2', 'country_id' => '39', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Hungary was 113 million liters (30 million gallons) representing  6% of gasoline demand. Ethanol production and Net Imports were 531 and -418 million liters (140  and -110 million gallons) correspondingly. Ethanol source is mainly Corn based.'],
            ['locale_id' => '2', 'country_id' => '40', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Ireland was 107 million liters (28 million gallons) representing  10% of gasoline demand. Ethanol production and Net Imports were 10 and 95 million liters (3 and 25 million gallons) correspondingly. Ethanol source is Cereals 100%.'],
            ['locale_id' => '2', 'country_id' => '41', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Italy was 277 million liters (73 million gallons) representing  2% of gasoline demand. Ethanol production and Net Imports were 71 and 206 million liters (19  and 54 million gallons) correspondingly. Ethanol sources are Wine and Second Generation Lignocelulosic ethanol. '],
            ['locale_id' => '2', 'country_id' => '42', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Latvia was 13 million liters (3 million gallons) representing 6% of gasoline demand. Net Imports were 13 million liters (3 million gallons) correspondingly. Ethanol source Cereals 100%.'],
            ['locale_id' => '2', 'country_id' => '43', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Lithuania was 200 million liters (53 million gallons) representing  42% of gasoline demand. Ethanol production and Net Imports were 96 and 101 million liters (25 and 27 million gallons) correspondingly. Ethanol sources are Corn 15% and Cereals 85%.'],
            ['locale_id' => '2', 'country_id' => '44', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Luxembourg was 24 million liters (6 million gallons) representing  4% of gasoline demand. Net Imports were 27 million liters (7 million gallons). Ethanol sources are Sugar Cane 80% and Corn 20%.'],
            ['locale_id' => '2', 'country_id' => '45', 'key' => 'ethanol_text', 'content' => 'E10 is allowed but Malta does not produce or consume bioethanol at a commercial level'],
            ['locale_id' => '2', 'country_id' => '46', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Netherlands was 500 million liters (132 million gallons) representing  11% of gasoline demand. Ethanol Net Imports were 695 million liters (0  and 184 million gallons) correspondingly. Ethanol sources are Sugar Cane 5% and Cereals 95%.'],
            ['locale_id' => '2', 'country_id' => '47', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Poland was 659 million liters (174 million gallons) representing  8% of gasoline demand. Ethanol production and Net Imports were 560 and 99 million liters (148  and 26 million gallons) correspondingly. Ethanol sources are Corn 57% and Cereals 43%.'],
            ['locale_id' => '2', 'country_id' => '48', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Portugal was 263 million liters (69 million gallons) representing  15% of gasoline demand. Portugal does not produce ethanol, supply is done through imports.  Local production plants are being built.'],
            ['locale_id' => '2', 'country_id' => '49', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Romania was 9 million liters (2.4 million gallons) representing  0.5% of gasoline demand. Ethanol Net Imports were 9 million liters (0  and 2.4 million gallons) correspondingly. Ethanol sources are Corn 28% and Cereals 72%.'],
            ['locale_id' => '2', 'country_id' => '50', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Slovakia was 80 million liters (21 million gallons) representing  9.3% of gasoline demand. Ethanol production and Net Imports were 166 and -87 million liters (44  and -23 million gallons) correspondingly. Ethanol source is Cereals 100%.'],
            ['locale_id' => '2', 'country_id' => '51', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Slovenia was 14 million liters (4 million gallons) representing  2.4% of gasoline demand. Ethanol production and Net Imports were 0 and 14 million liters (0  and 4 million gallons) correspondingly. Ethanol source is Cereals 100%.'],
            ['locale_id' => '2', 'country_id' => '52', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Spain was 315 million liters (83 million gallons) representing  3.5% of gasoline demand. Ethanol production and Net Imports were 540 and -333 million liters (143  and -88 million gallons) correspondingly. Ethanol sources are Corn 60%, Cereals 25% and Sugar Beet/Wine 40%.'],
            ['locale_id' => '2', 'country_id' => '53', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in Sweden was 335 million liters (89 million gallons) representing  12.5% of gasoline demand. Ethanol production and Net Imports were 62 and 273 million liters (16  and 72 million gallons) correspondingly. Ethanol sources are Wood 25% and Cereals 75%.'],
            ['locale_id' => '2', 'country_id' => '54', 'key' => 'ethanol_text', 'content' => 'In 2025, ethanol consumption in United Kingdom was 1,551 million liters (410 million gallons) representing  10.4% of gasoline demand. Ethanol production and Net Imports were 480 and 1,071 million liters (127  and 283 million gallons) correspondingly. Ethanol sources are Corn 84%, Cereals 13% and Sugar Beet 3%.'],



        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {

        DB::table('dynamic_tools_texts')->where('country_id', '>', 26)->delete();
    }
}
