<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AsiaProfiles extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
          DB::table('profiles')->insert([

            ['country_id' => '59', 'locale_id' => '2', 'name' => 'JIS K 2202', 'implementation_date' => '2023', 'applicability' => 'Nationwide', 'selected_grade' => 'Gasoline 1', 'benzene_content' => '< 1 %v/v', 'aromatics' => 'Typical Range 18-36%', 'olefins' => '', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 89', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<1,3 % m/m', 'ethanol' => '<3 %v/v', 'rvp_summer' => '<> 45 - 93 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '<7 %v/v', 'ethers' => '', 'order' => '1', 'content' => ''],
            ['country_id' => '59', 'locale_id' => '2', 'name' => 'JIS K 2202', 'implementation_date' => '2023', 'applicability' => 'Nationwide', 'selected_grade' => 'Gasoline 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => 'Typical Range 18-36%', 'olefins' => '', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 96', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<1,3 % m/m', 'ethanol' => '<3 %v/v', 'rvp_summer' => '<> 45 - 93 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '<7 %v/v', 'ethers' => '', 'order' => '2', 'content' => ''],
            ['country_id' => '59', 'locale_id' => '2', 'name' => 'JIS K 2202', 'implementation_date' => '2023', 'applicability' => 'Nationwide', 'selected_grade' => 'Gasoline 1(E)', 'benzene_content' => '< 1 %v/v', 'aromatics' => 'Typical Range 18-36%', 'olefins' => '', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 89', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<>1,3- 3,5 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '<> 45 - 93 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '<7 %v/v', 'ethers' => '', 'order' => '3', 'content' => ''],
            ['country_id' => '59', 'locale_id' => '2', 'name' => 'JIS K 2202', 'implementation_date' => '2023', 'applicability' => 'Nationwide', 'selected_grade' => 'Gasoline 2(E)', 'benzene_content' => '< 1 %v/v', 'aromatics' => 'Typical Range 18-36%', 'olefins' => '', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2,0 mg/l', 'ron' => '> 96', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<>1,3- 3,5 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '<> 45 - 93 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '<7 %v/v', 'ethers' => '', 'order' => '4', 'content' => ''],
            ['country_id' => '56', 'locale_id' => '2', 'name' => 'MS 118-3:2011', 'implementation_date' => '2011', 'applicability' => 'Nationwide', 'selected_grade' => 'RON 95', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '', 'ron' => '> 95', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '', 'ethanol' => '', 'rvp_summer' => '<> 60  - 70 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '1', 'content' => ''],
            ['country_id' => '56', 'locale_id' => '2', 'name' => 'MS 118-3:2011', 'implementation_date' => '2011', 'applicability' => 'Nationwide', 'selected_grade' => 'RON 97', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '', 'ron' => '> 97', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '', 'ethanol' => '', 'rvp_summer' => '<> 60  - 70 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '2', 'content' => ''],
            ['country_id' => '60', 'locale_id' => '2', 'name' => 'Clean Air Conservation Acta', 'implementation_date' => '2009', 'applicability' => 'Nationwide', 'selected_grade' => 'RON 91', 'benzene_content' => '< 0,7 %v/v', 'aromatics' => '< 24 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 13 mg/l', 'magnanese' => '', 'ron' => '> 91', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<> 0,5 - 2,3 % m/m', 'ethanol' => '', 'rvp_summer' => '60 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '1', 'content' => ''],
            ['country_id' => '60', 'locale_id' => '2', 'name' => 'Clean Air Conservation Acta', 'implementation_date' => '2009', 'applicability' => 'Nationwide', 'selected_grade' => 'RON 94', 'benzene_content' => '< 0,7 %v/v', 'aromatics' => '< 24 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 13 mg/l', 'magnanese' => '', 'ron' => '> 94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<> 0,5 - 2,3 % m/m', 'ethanol' => '', 'rvp_summer' => '60 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '2', 'content' => ''],
            ['country_id' => '58', 'locale_id' => '2', 'name' => 'Mobile Pollution Source Fuel Composition Control Standard Regulation', 'implementation_date' => '2024', 'applicability' => 'Nationwide', 'selected_grade' => 'RON 92', 'benzene_content' => '< 0,8 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '', 'ron' => '> 92', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<3,24 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '<> 45 - 66.9 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '1', 'content' => ''],
            ['country_id' => '58', 'locale_id' => '2', 'name' => 'Mobile Pollution Source Fuel Composition Control Standard Regulation', 'implementation_date' => '2024', 'applicability' => 'Nationwide', 'selected_grade' => 'RON 95', 'benzene_content' => '< 0,8 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '', 'ron' => '> 95', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<3,24 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '<> 45 - 66.9 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '2', 'content' => ''],
            ['country_id' => '58', 'locale_id' => '2', 'name' => 'Mobile Pollution Source Fuel Composition Control Standard Regulation', 'implementation_date' => '2024', 'applicability' => 'Nationwide', 'selected_grade' => 'RON 98', 'benzene_content' => '< 0,8 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '', 'ron' => '> 98', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<3,24 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '<> 45 - 66.9 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '3', 'content' => ''],
            ['country_id' => '57', 'locale_id' => '2', 'name' => 'B.E. 2557 (2014)					', 'implementation_date' => '2014', 'applicability' => 'Nationwide', 'selected_grade' => 'Gasohol E10 (91)', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '', 'ron' => '> 91', 'mon' => '> 80', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '', 'ethanol' => '<10 %v/v', 'rvp_summer' => '62 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '1', 'content' => ''],
            ['country_id' => '57', 'locale_id' => '2', 'name' => 'B.E. 2557 (2014)					', 'implementation_date' => '2014', 'applicability' => 'Nationwide', 'selected_grade' => 'Gasohol E10 (95)', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '', 'ron' => '> 95', 'mon' => '> 84', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '', 'ethanol' => '<10 %v/v', 'rvp_summer' => '62 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '2', 'content' => ''],
            ['country_id' => '57', 'locale_id' => '2', 'name' => 'B.E. 2557 (2014)					', 'implementation_date' => '2014', 'applicability' => 'Nationwide', 'selected_grade' => 'Gasohol E20 (95)', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '', 'ron' => '> 95', 'mon' => '> 84', 'aki' => '', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '', 'ethanol' => '<20 %v/v', 'rvp_summer' => '62 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '3', 'content' => ''],
            ['country_id' => '55', 'locale_id' => '2', 'name' => 'QCVN 01:2022/BKHCN', 'implementation_date' => '2022', 'applicability' => 'Nationwide', 'selected_grade' => 'RON 92', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 5,0 mg/l', 'ron' => '> 92', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<2,7 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '< 62 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '1', 'content' => ''],
            ['country_id' => '55', 'locale_id' => '2', 'name' => 'QCVN 01:2022/BKHCN', 'implementation_date' => '2022', 'applicability' => 'Nationwide', 'selected_grade' => 'RON 95', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 5,0 mg/l', 'ron' => '> 95', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<2,7 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '< 62 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '2', 'content' => ''],
            ['country_id' => '55', 'locale_id' => '2', 'name' => 'QCVN 01:2022/BKHCN', 'implementation_date' => '2022', 'applicability' => 'Nationwide', 'selected_grade' => 'RON 97', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 5,0 mg/l', 'ron' => '> 97', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '<2,7 % m/m', 'ethanol' => '<10 %v/v', 'rvp_summer' => '< 62 kPa', 'rvp_winter' => '0', 'rvp_transition' => '0', 'mtbe' => '', 'ethers' => '', 'order' => '3', 'content' => ''],

        ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('profiles')->where('country_id', '>', 54)->delete();
    }
}
