<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddColumnContinentIdToProfiles extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {

        // Schema::dropIfExists('profiles');

        DB::table('profiles')->insert([
            ['country_id' => '27', 'locale_id' => '2', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'North Zone', 'selected_grade' => 'Gasoline Grade 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '2', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'North Zone', 'selected_grade' => 'Gasoline Grade 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '2', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'Central Zone', 'selected_grade' => 'Gasoline Grade 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '<> 45 - 80 kPa', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '2', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'Central Zone', 'selected_grade' => 'Gasoline Grade 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '<> 45 - 80 kPa', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '2', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'South Zone', 'selected_grade' => 'Gasoline Grade 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 45 - 80 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '5', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '2', 'name' => 'Resolution 576/2019', 'implementation_date' => '2019', 'applicability' => 'South Zone', 'selected_grade' => 'Gasoline Grade 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 45 - 80 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '6', 'content' => 'NULL'],
            ['country_id' => '28', 'locale_id' => '2', 'name' => 'Supreme Decree 2741', 'implementation_date' => '2016', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 3%v/v (2,7%v/v for E12 in summer)', 'aromatics' => '< 42 % v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 85', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '-', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '28', 'locale_id' => '2', 'name' => 'Supreme Decree 2741', 'implementation_date' => '2016', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '< 3%v/v (2,7%v/v for E12 in summer)', 'aromatics' => '< 48 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '-', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '28', 'locale_id' => '2', 'name' => 'Resolution 121-18', 'implementation_date' => '2018', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline for E8', 'benzene_content' => '< 3%v/v (2,7%v/v for E12 in summer)', 'aromatics' => '< 42 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 85', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< 8 %v/v', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '28', 'locale_id' => '2', 'name' => 'Resolution 042-19', 'implementation_date' => '2019', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline for E12', 'benzene_content' => '< 3%v/v (2,7%v/v for E12 in summer)', 'aromatics' => '< 42 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 92', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< 12 %v/v', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '59', 'locale_id' => '2', 'name' => 'PPDA DS31', 'implementation_date' => '2017', 'applicability' => 'Metropolitan Region', 'selected_grade' => 'G93', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '12 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '93', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 55 kPa', 'rvp_winter' => '<> 69 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '59', 'locale_id' => '2', 'name' => 'PPDA DS31', 'implementation_date' => '2017', 'applicability' => 'Metropolitan Region', 'selected_grade' => 'G97', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '12 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '97', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 55 kPa', 'rvp_winter' => '<> 69 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '59', 'locale_id' => '2', 'name' => ' DS 60', 'implementation_date' => '2012', 'applicability' => 'Rest of the country', 'selected_grade' => 'G93', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '20 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '93', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 69 kPa, <> 83 kPa (Magallanes y región Antártica)', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '59', 'locale_id' => '2', 'name' => ' DS 60', 'implementation_date' => '2012', 'applicability' => 'Rest of the country', 'selected_grade' => 'G97', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '20 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '97', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 69 kPa, <> 83 kPa (Magallanes y región Antártica)', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '61', 'locale_id' => '2', 'name' => 'Resolution 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 1,0 %v/v', 'aromatics' => '< 28 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 84', 'mon' => '-', 'aki' => '> 81', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '61', 'locale_id' => '2', 'name' => 'Resolution 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Extra', 'benzene_content' => '< 2,0 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 93', 'mon' => '-', 'aki' => '> 91', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '61', 'locale_id' => '2', 'name' => 'Resolution 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Regular E10', 'benzene_content' => '< 0,9 %v/v', 'aromatics' => '< 25 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 89', 'mon' => '-', 'aki' => '> 84', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '61', 'locale_id' => '2', 'name' => 'Resolution 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Whole country', 'selected_grade' => 'Gasoline Extra E10', 'benzene_content' => '< 1,8 %v/v', 'aromatics' => '< 31,5 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 97', 'mon' => '-', 'aki' => '> 94', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '54', 'locale_id' => '2', 'name' => 'NORDOM 476 3rd Revision', 'implementation_date' => '2015', 'applicability' => 'Whole country', 'selected_grade' => 'Regular Gasoline', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 89', 'mon' => '> 76', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'oxygen_content' => '', 'ethanol' => '', 'rvp_summer' => '< 61 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '54', 'locale_id' => '2', 'name' => 'NORDOM 476 3rd Revision', 'implementation_date' => '2015', 'applicability' => 'Whole country', 'selected_grade' => 'Premium Gasoline', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 95', 'mon' => '> 82', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'oxygen_content' => '', 'ethanol' => '', 'rvp_summer' => '< 61 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '54', 'locale_id' => '2', 'name' => 'NORDOM 476 3rd Revision', 'implementation_date' => '2015', 'applicability' => 'Whole country', 'selected_grade' => 'Oxigenated Regular Gasoline', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 90', 'mon' => '> 77', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'oxygen_content' => '< 3.5 %m/m', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '54', 'locale_id' => '2', 'name' => 'NORDOM 476 3rd Revision', 'implementation_date' => '2015', 'applicability' => 'Whole country', 'selected_grade' => 'Oxigenated Premium Gasoline', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 96', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'oxygen_content' => '< 3.5 %m/m', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '2', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Mexico City', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 25 %v/v ', 'olefins' => '< 10 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => 'Not allowed', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa ', 'mtbe' => '', 'ethers' => '-', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '2', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Mexico City', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 25 %v/v ', 'olefins' => '< 10 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => 'Not allowed', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa ', 'mtbe' => '', 'ethers' => '-', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '2', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Guadalajara and Monterrey', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 32 %v/v', 'olefins' => '< 11,9 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => 'Not allowed', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa  Guadalajara', 'mtbe' => '', 'ethers' => '-', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '2', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Guadalajara and Monterrey', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '22,6% v/v', 'olefins' => '< 11,9 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => 'Not allowed', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa  Guadalajara', 'mtbe' => '', 'ethers' => '-', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '2', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Rest of the country', 'selected_grade' => 'Gasoline Regular', 'benzene_content' => '< 2 %v/v ', 'aromatics' => 'Report', 'olefins' => 'Report', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '> 5,8 %v/v', 'rvp_summer' => '< 69 kPa North, < 62 kPa Center, South, Pacific', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '5', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '2', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Rest of the country', 'selected_grade' => 'Gasoline Premium', 'benzene_content' => '< 2 %v/v ', 'aromatics' => '22,6% v/v', 'olefins' => '< 2,5 mg/l', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '> 5,8 %v/v', 'rvp_summer' => '< 69 kPa North, < 62 kPa Center, South, Pacific', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '6', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '4', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Norte', 'selected_grade' => 'Gasolina Grado 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '4', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Norte', 'selected_grade' => 'Gasolina Grado 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '4', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Central', 'selected_grade' => 'Gasolina Grado 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '<> 45 - 80 kPa', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '4', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Central', 'selected_grade' => 'Gasolina Grado 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 35 - 70 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '<> 45 - 80 kPa', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '4', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Sur', 'selected_grade' => 'Gasolina Grado 2', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 93', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 150 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 45 - 80 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '5', 'content' => 'NULL'],
            ['country_id' => '27', 'locale_id' => '4', 'name' => 'Resolución 576/2019', 'implementation_date' => '2019', 'applicability' => 'Zona Sur', 'selected_grade' => 'Gasolina Grado 3', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 40 %v/v', 'olefins' => '-', 'lead_content' => '< 5 mg/l', 'magnanese' => '< 2.5 mg/l', 'ron' => '> 97', 'mon' => '> 85', 'aki' => '', 'sulfur_content' => '< 10 mg/kg', 'oxygen_content' => '< 4.5 %m/m', 'ethanol' => '<> 12 - 14 %v/v', 'rvp_summer' => '<> 45 - 80 kPa', 'rvp_winter' => '<> 55 - 90 kPa', 'rvp_transition' => '', 'mtbe' => '< 15 %v/v', 'ethers' => '< 22 %v/v', 'order' => '6', 'content' => 'NULL'],
            ['country_id' => '28', 'locale_id' => '4', 'name' => 'Decreto supremo 2741', 'implementation_date' => '2016', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '< 3%v/v (2,7%v/v para E12 en verano)', 'aromatics' => '< 42 % v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 85', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '-', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '28', 'locale_id' => '4', 'name' => 'Decreto supremo 2741', 'implementation_date' => '2016', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '< 3%v/v (2,7%v/v para E12 en verano)', 'aromatics' => '< 48 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 95', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '-', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '28', 'locale_id' => '4', 'name' => 'Resolución 121-18', 'implementation_date' => '2018', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina para E8', 'benzene_content' => '< 3%v/v (2,7%v/v para E12 en verano)', 'aromatics' => '< 42 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 85', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< 8 %v/v', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '28', 'locale_id' => '4', 'name' => 'Resolución 042-19', 'implementation_date' => '2019', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina para E12', 'benzene_content' => '< 3%v/v (2,7%v/v para E12 en verano)', 'aromatics' => '< 42 %v/v', 'olefins' => '< 18 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 18 mg/l', 'ron' => '> 92', 'mon' => '-', 'aki' => '', 'sulfur_content' => '< 500 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '< 12 %v/v', 'rvp_summer' => '<> 48-79 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '54', 'locale_id' => '4', 'name' => 'NORDOM 476 3era Revision', 'implementation_date' => '2015', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Regular', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 89', 'mon' => '> 76', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'oxygen_content' => '', 'ethanol' => '', 'rvp_summer' => '< 61 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '54', 'locale_id' => '4', 'name' => 'NORDOM 476 3era Revision', 'implementation_date' => '2015', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Premium', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 95', 'mon' => '> 82', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'oxygen_content' => '', 'ethanol' => '', 'rvp_summer' => '< 61 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '54', 'locale_id' => '4', 'name' => 'NORDOM 476 3era Revision', 'implementation_date' => '2015', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina regular oxigenada', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 90', 'mon' => '> 77', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'oxygen_content' => '< 3.5 %m/m', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '54', 'locale_id' => '4', 'name' => 'NORDOM 476 3era Revision', 'implementation_date' => '2015', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina premium oxigenada', 'benzene_content' => '-', 'aromatics' => '-', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '< 8,3 mg/l ', 'ron' => '> 96', 'mon' => '> 83', 'aki' => '', 'sulfur_content' => '< 1.500 mg/kg', 'oxygen_content' => '< 3.5 %m/m', 'ethanol' => '< 10 %v/v', 'rvp_summer' => '< 69 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '59', 'locale_id' => '4', 'name' => 'PPDA DS31', 'implementation_date' => '2017', 'applicability' => 'Region Metropolitana', 'selected_grade' => 'G93', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '12 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '93', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 55 kPa', 'rvp_winter' => '<> 69 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '59', 'locale_id' => '4', 'name' => 'PPDA DS31', 'implementation_date' => '2017', 'applicability' => 'Region Metropolitana', 'selected_grade' => 'G97', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '12 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '97', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 55 kPa', 'rvp_winter' => '<> 69 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '59', 'locale_id' => '4', 'name' => ' DS 60', 'implementation_date' => '2012', 'applicability' => 'Resto del país', 'selected_grade' => 'G93', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '20 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '93', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 69 kPa, <> 83 kPa (Magallanes y región Antártica)', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '59', 'locale_id' => '4', 'name' => ' DS 60', 'implementation_date' => '2012', 'applicability' => 'Resto del país', 'selected_grade' => 'G97', 'benzene_content' => '< 1 %v/v', 'aromatics' => '< 38 %v/v', 'olefins' => '20 %v/v', 'lead_content' => '< 0,013 g/l', 'magnanese' => 'Reportar', 'ron' => '97', 'mon' => 'Reportar', 'aki' => '', 'sulfur_content' => '< 15 mg/kg', 'oxygen_content' => '< 2 %m/m', 'ethanol' => '<5 %v/v', 'rvp_summer' => '<> 69 kPa, <> 83 kPa (Magallanes y región Antártica)', 'rvp_winter' => '<> 45 - 80 kPa', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '61', 'locale_id' => '4', 'name' => 'Resolución 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Corriente', 'benzene_content' => '< 1,0 %v/v', 'aromatics' => '< 28 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 84', 'mon' => '-', 'aki' => '> 81', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '61', 'locale_id' => '4', 'name' => 'Resolución 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Extra', 'benzene_content' => '< 2,0 %v/v', 'aromatics' => '< 35 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 93', 'mon' => '-', 'aki' => '> 91', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '61', 'locale_id' => '4', 'name' => 'Resolución 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Corriente E10', 'benzene_content' => '< 0,9 %v/v', 'aromatics' => '< 25 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 89', 'mon' => '-', 'aki' => '> 84', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '61', 'locale_id' => '4', 'name' => 'Resolución 40103 de 2021', 'implementation_date' => '2021', 'applicability' => 'Todo el país', 'selected_grade' => 'Gasolina Extra E10', 'benzene_content' => '< 1,8 %v/v', 'aromatics' => '< 31,5 %v/v', 'olefins' => '-', 'lead_content' => '< 0,013 g/l', 'magnanese' => '-', 'ron' => '> 97', 'mon' => '-', 'aki' => '> 94', 'sulfur_content' => '< 50 mg/kg', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '<> 9,5 - 10,5 %v/v', 'rvp_summer' => '<> 65 kPa', 'rvp_winter' => '', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '4', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Ciudad de México', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 25 %v/v ', 'olefins' => '< 10 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => 'No se permite ', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa ', 'mtbe' => '', 'ethers' => '-', 'order' => '1', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '4', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Ciudad de México', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 25 %v/v ', 'olefins' => '< 10 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => 'No se permite ', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa ', 'mtbe' => '', 'ethers' => '-', 'order' => '2', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '4', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Guadalajara y Monterrey', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '< 32 %v/v', 'olefins' => '< 11,9 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => 'No se permite ', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa  Guadalajara', 'mtbe' => '', 'ethers' => '-', 'order' => '3', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '4', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Guadalajara y Monterrey', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '< 1 %v/v ', 'aromatics' => '22,6% v/v', 'olefins' => '< 11,9 %v/v ', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => 'No se permite ', 'rvp_summer' => '< 62 kPa ', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '< 54 kPa  Guadalajara', 'mtbe' => '', 'ethers' => '-', 'order' => '4', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '4', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Resto del país', 'selected_grade' => 'Gasolina regular', 'benzene_content' => '< 2 %v/v ', 'aromatics' => 'Reporte', 'olefins' => 'Reporte', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '', 'mon' => '82', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 3,7 %m/m', 'ethanol' => '> 5,8 %v/v', 'rvp_summer' => '< 69 kPa Norte, < 62 kPa centro, sur, Pacífico', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '5', 'content' => 'NULL'],
            ['country_id' => '52', 'locale_id' => '4', 'name' => 'NOM-016-CRE-2016', 'implementation_date' => '2016', 'applicability' => 'Resto del país', 'selected_grade' => 'Gasolina premium', 'benzene_content' => '< 2 %v/v ', 'aromatics' => '22,6% v/v', 'olefins' => '< 2,5 mg/l', 'lead_content' => '-', 'magnanese' => '0 mg/l', 'ron' => '94', 'mon' => '', 'aki' => '', 'sulfur_content' => '< 80 mg/kg', 'oxygen_content' => '< 2,7 %m/m', 'ethanol' => '> 5,8 %v/v', 'rvp_summer' => '< 69 kPa Norte, < 62 kPa centro, sur, Pacífico', 'rvp_winter' => '< 79 kPa ', 'rvp_transition' => '', 'mtbe' => '', 'ethers' => '-', 'order' => '6', 'content' => 'NULL'],
            
        ]);

        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        
    }
}
